### ISSUE TITLE
'Invaild plugin.yml' when starting server

### ISSUE THREAD

**Issue by NoahCothran** [pop4959/Chunky#138]
When trying to start my server with Chunky in the plugins directory
![error](https://user-images.githubusercontent.com/89223947/140440351-238e11f3-ed03-48ba-b421-bb7f4a21b921.PNG)

I have not had any other errors until trying to use Chunky. I removed all other plugins, updated to the latest version of PaperMC, and did a clean install in another directory, and this error still showed up. I tried versions 1.2.86 and 1.2.124 of Chunky.

I am running on a Raspberry Pi 4 running Raspberry Pi OS 64-bit. I am running OpenJDK 16.0.2.

**Comment by pop4959** [comment]
Usually this means the plugin was not downloaded correctly. If you check the hash of the files you downloaded you should be able to check if it matches for the version you downloaded. The hashes can be found [here](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/188/artifact/bukkit/build/libs/Chunky-Bukkit-1.2.86.jar/*fingerprint*/) and [here](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/225/artifact/bukkit/build/libs/Chunky-1.2.124.jar/*fingerprint*/) for 1.2.86 and 1.2.124.

If you're still having trouble come by the #chunky channel in the [Discord server](https://discord.gg/ZwVJukcNQG).
