### ISSUE TITLE
crash which bricked world

### ISSUE THREAD

**Issue by Reshirou** [pop4959/Chunky#139]
Crashed while genning End. This was the third pregen, after I did the Overworld and Nether.

Didn't really seem like a big deal, except for a few restarts afterward it auto hard crashed right after preparing spawn area. Seems to work fine now. Still figure it's worth sending the crash report.

Sorry that I forgot to add NotEnoughCrashes to my server!

https://pastebin.com/ScCyLwMK

**Comment by Reshirou** [comment]
Update: hah nevermind it's a bricked world; can't join or it auto crashes.

Big RIP but not the end of the world. Well, the end of THAT world but not every world.

**Comment by pop4959** [comment]
From the crash log it looks like this is caused by the betterendforge mod. You may want to report it to the authors, especially if you're getting stuck in a crash loop because of it.

Relevant snippet:
```
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.vector.Vector3f.func_195904_b(FFF)V
	at mod.beethoven92.betterendforge.common.world.feature.ThinArchFeature.lambda$generate$0(ThinArchFeature.java:74) ~
```

**Comment by Reshirou** [comment]
Makes sense, will do thank you.

**Comment by pop4959** [comment]
No problem, good luck!
