### ISSUE TITLE
Crash with fabric-carpet

### ISSUE THREAD

**Issue by Oliver-makes-code** [pop4959/Chunky#147]
When I have [fabric-carpet](https://github.com/gnembon/fabric-carpet) installed, it causes chunky to crash because the config is null.

**Comment by Oliver-makes-code** [comment]
This was due to a different mod and was resolved

**Comment by pop4959** [comment]
Glad to hear it wasn't an issue with this mod; it would be rather unlikely as we don't use any mixin injects.

Just out of curiosity, what was the solution?
