### ISSUE TITLE
Feature request: basic placeholder support

### ISSUE THREAD

**Issue by mrfloris** [pop4959/Chunky#159]
Hey :)

Merry Christmas, this is a reminder after a quick Discord DM so we don't forget about basic PlaceholderAPI support for one or two basic placeholders.

The reason for a placeholder is that we can offload quite a bit of automation to other plugins like CMI and be more nitpicky about it.

For example, in CMI I can use CMI-scheduler and CMI-specialized-commands combo to check against values of placeholders, so for example if there are less than x players online, and tps is bigger than a certain value, we can check if chunky is not yet running and start it. And another scheduler can check once in a while if the player count over a certain amount or that the tps is below a certain a amount of pause the task if it is running. 

Currently a more crude brute-forcing approach is used, but switching worlds etc will cause unexpected results and unreliable results. 

Anyway, something like: `%chunky_status` returning `true`|`false` would also help.

Ideally we'd know if it is running, processing chunks. or running, but paused. or if it is not running. And ideally we'd know which worlds, so we can go pause processing a world until it's done, and then automate the task to go to another world. 

Yes, auto pausing and auto starting, and spreading the world load will take longer, but that is fine. Offloading live-worlds isn't always possible on big(ger) servers, but having a bit of control over the 'status' of chunky will help us slowly go through it. And we can offload the worlds we CAN offload to a test server.

**Comment by pop4959** [comment]
Hey @mrfloris, it's been a while! Thank you for your patience.

I have finally gotten around to creating an expansion for both Chunky & ChunkyBorder. They will (hopefully) be published on PAPI eCloud as soon as I can get an account. For now you can download a copy of them on [CodeMC](https://ci.codemc.io/job/pop4959/job/ChunkyPlaceholderExpansion/) and install manually.

Documentation (for now):

**Chunky**

Conditional placeholders.
```
%chunky_task_pregen_exists_<world>%
%chunky_task_pregen_running_<world>%
```
Task configuration placeholders. These may return a default value when the task doesn't exist.
```
%chunky_task_pregen_cancelled_<world>%
%chunky_task_pregen_centerx_<world>%
%chunky_task_pregen_centerz_<world>%
%chunky_task_pregen_radius_<world>%
%chunky_task_pregen_radiusx_<world>%
%chunky_task_pregen_radiusz_<world>%
%chunky_task_pregen_count_<world>%
%chunky_task_pregen_pattern_<world>%
%chunky_task_pregen_shape_<world>%
%chunky_task_pregen_time_<world>%
```
Task progress placeholders. These are only accessible when a task is currently running.
```
%chunky_task_pregen_world_<world>%
%chunky_task_pregen_chunks_<world>%
%chunky_task_pregen_complete_<world>%
%chunky_task_pregen_percent_<world>%
%chunky_task_pregen_hours_<world>%
%chunky_task_pregen_minutes_<world>%
%chunky_task_pregen_seconds_<world>%
%chunky_task_pregen_rate_<world>%
%chunky_task_pregen_x_<world>%
%chunky_task_pregen_z_<world>%
```

**ChunkyBorder**

Conditional placeholders.
```
%chunkyborder_border_exists_<world>%
```

Border configuration placeholders. These are only accessible when a border exists.
```
%chunkyborder_border_world_<world>%
%chunkyborder_border_centerx_<world>%
%chunkyborder_border_centerz_<world>%
%chunkyborder_border_radius_<world>%
%chunkyborder_border_radiusx_<world>%
%chunkyborder_border_radiusz_<world>%
%chunkyborder_border_shape_<world>%
%chunkyborder_border_wrap_<world>%
```

I hope you find these useful. 😃

**Comment by mrfloris** [comment]
That's awesome. Thank you!

**Comment by pop4959** [comment]
It's now available on eCloud:
https://api.extendedclip.com/expansions/chunky/
https://api.extendedclip.com/expansions/chunkyborder/
