### ISSUE TITLE
A question to the generation

### ISSUE THREAD

**Issue by PortableGames** [pop4959/Chunky#170]
Why does chunky skip some chunks during generation?
![Screenshot_20220110_214539](https://user-images.githubusercontent.com/89090940/148837778-ed82950e-3648-476e-8fea-a22f4d3a1d99.jpg)

**Comment by PortableGames** [comment]
And how can I regenerate these chunks without starting the whole process again?

**Comment by pop4959** [comment]
> Why does chunky skip some chunks during generation?

If you've pre-generated the region already, the black spots on your map are probably a result of it not having rendered it yet, and not an issue with Chunky.

> And how can I regenerate these chunks without starting the whole process again?

Simply run the task again. It will generate any chunks that are missing in your world, if there are any. This will usually be a faster process than the first time, if most or all of the chunks are already generated.
