### ISSUE TITLE
Crashes when not focused on console window

### ISSUE THREAD

**Issue by TristanKing0** [pop4959/Chunky#173]
Happens consistently. If I leave the console window open and focused it runs fine. If I go on to another window it crashes.
[crash-2022-02-21_10.57.22-server.txt](https://github.com/pop4959/Chunky/files/8108613/crash-2022-02-21_10.57.22-server.txt)

Edit: Uploaded wrong crash report originally.

**Comment by pop4959** [comment]
A watchdog crash on its own doesn't say much, especially if you don't have evidence that it's at all related to chunky. All it tells you is that your server stopped responding (which could just be the game itself, another mod, something else you are doing on your computer, etc).

If you need further help troubleshooting please visit our [Discord](https://discord.gg/ZwVJukcNQG). Keep in mind that at the time of posting this it is quite late so you may be waiting a bit for a response.

**Comment by TristanKing0** [comment]
The issue was caused by Windows 10/11's "Quick Edit Mode" in the console properties, which is set by default and is stupid. Just FYI in case anyone has this issue and reads this.

**Comment by pop4959** [comment]
> The issue was caused by Windows 10/11's "Quick Edit Mode" in the console properties, which is set by default and is stupid. Just FYI in case anyone has this issue and reads this.


Thanks for the follow-up! That makes a lot of sense actually, I've gotten tripped up on that before when using Windows as well.
