### ISSUE TITLE
Command Line Interpretation

### ISSUE THREAD

**Issue by xxbones21xx** [pop4959/Chunky#176]
Does you mod interpret "chunky radius 10k" the same as "chunky radius 10000" ? Further clarification, does that value represent blocks or chunks?

**Comment by pop4959** [comment]
Yes, the `k` suffix is per 1000 blocks. The `c` suffix can also be used to represent chunks instead (measures of 16). Chunky will automatically do the conversions for you though (rounding up to the nearest chunk if necessary).

More examples [here](https://github.com/pop4959/Chunky/wiki/Commands#radius).

If you have any other questions feel free to drop by the #chunky channel in our [Discord server](https://discord.gg/ZwVJukcNQG).
