### ISSUE TITLE
Feature Request: Polygon Borders/Render Regions

### ISSUE THREAD

**Issue by itswilven** [pop4959/Chunky#178]
It would be great to have an option to define a polygon region that is rendered or to act as a player world border. 

I imagine it working similar to the Dynmap area marker commands or worldguard in which you run a command to define the individual corners of the shape. It could allow for more unique shapes such as L shapes or crosses.

**Comment by pop4959** [comment]
Possibly a better alternative to #157. Any thoughts @Zeklandia?

Do you have an example of the dynmap/worldguard commands for reference?

Right now I'm kind of thinking along the lines of:
```
chunky shape polygon <coordinates (3+)...>
```

**Comment by Zeklandia** [comment]
Hypothetically, yes. Making a shape with a 'hole' would be a little harder but still possible.

**Comment by pop4959** [comment]
> Hypothetically, yes. Making a shape with a 'hole' would be a little harder but still possible.

Of course, just trying to explore options here. To that end, I was thinking it almost makes sense to just have the ability to set a region to "skip", unless you had anything else in mind beside that.

For completely weird/custom shapes, I almost think that might honestly be a bit out of scope for chunky itself, but perhaps something that would still be supported via API.

**Comment by pop4959** [comment]
I've decided that there is too much maintenance burden here to consider adding custom shapes to the API at the moment, however in 0cc7d2219066bf5323756685c1a29d9d8bfe004f there is now support for registering custom shapes internally. So it is possible to hook into Chunky directly at startup and register a custom shape implementation which can be used for pre-generation and as a border. I'm hoping that this is a good middle ground for the few servers with specific needs.
