### ISSUE TITLE
Feature Request: inverse trim command

### ISSUE THREAD

**Issue by danielledeleo** [pop4959/Chunky#195]
I would like to delete the contents of a shape within my world for the purpose of regenerating it, but I think a general deletion command is a nice thing to have. I think what I want is pretty much just a negation of [this function in the existing trim command](https://github.com/pop4959/Chunky/blob/master/common/src/main/java/org/popcraft/chunky/command/TrimCommand.java#L142-L153).

**Comment by pop4959** [comment]
Trivially the negation there does actually work, but it needs to be negated for both boundary checks in that class.

I've already got this feature as a "nice to have" in my personal to-do list. Originally trim was just added as a direct port for the trim feature in the old WorldBorder plugin for feature parity. Someone from the #chunky channel in our [Discord server](https://discord.gg/ZwVJukcNQG) has been working on putting together a PR to more properly implement that functionality, as well as fix some other gotchas with trim. I'm not sure how far along that is at the moment.

As an alternative, [mcaselector](https://github.com/Querz/mcaselector) exists and has a powerful selection GUI which makes deleting chunks a lot more accurate and less error prone. It's also generally better/easier to delete chunks with the server offline (and anyway, if the server is online, it should be restarted for data consistency).

Hopefully that might help, but if not (for example if downloading and re-uploading your world to process it is prohibitive) join the Discord server and I can get you access to a functional (but not publicly released) build that does implement the 'basic' reverse trim functionality. Or you can do it yourself by changing the 2 lines mentioned. 😛 

Will leave this open to track progress.

**Comment by pop4959** [comment]
This has been implemented in https://github.com/pop4959/Chunky/commit/66179d4a451ff0b32127ddd6af3cb6cd9d1a257b as an additional argument passed to the trim command.
