### ISSUE TITLE
Only Pregenerates 2 dimensions at a time

### ISSUE THREAD

**Issue by spoorn** [pop4959/Chunky#197]
Using [1.2.164](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator/files/3579660) for 1.18.2, if I trigger tasks to pregen 4 dimensions (nether, end, overworld, twilight forest), it only pregens 2 at a time.  It seems to only be pregenerating overworld and the end.  If I cancel and only trigger pregen tasks for twilight forest and nether, it works fine.

Is there some limitation to how many dimensions can be pregenerated at the same time?

**Comment by spoorn** [comment]
It also sometimes drops down to only pregenerating the overworld only, even though the other tasks are still there

**Comment by pop4959** [comment]
There are no limitations built into chunky. It depends entirely on the support of the server platform you are running on. For example, on Paper all 3 vanilla dimensions can be generated simultaneously. On Fabric/Forge (without mods essentially vanilla) these kinds of restrictions have been observed. As far as I recall, this became more of an issue after Minecraft 1.18.

You'll have to figure out what works on your server. If you have any other questions, feel free to join the [Discord server](https://discord.gg/ZwVJukcNQG).
