### ISSUE TITLE
Suggestion: Trim feature

### ISSUE THREAD

**Issue by ArtifactyNight** [pop4959/Chunky#20]
can you add **Trim feature** in Chunky plugin please?
like **Worldborder plugin** trim options

(https://shockbyte.com/billing/knowl...Minecraft-World-Using-WorldBorder-Plugin.html)

it's useful for make world is less storage size

**Comment by Zischbum** [comment]
Can you add the trim feature soon ?

**Comment by pop4959** [comment]
This feature is available now in the development builds on [CodeMC](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/), and should be included in the next release on Spigot. It's been tested by a few people already and it sounds like it works just fine, so if you'd like to try it at this point I'd say go ahead (but still make a backup of your server just in case). 😃
