### ISSUE TITLE
[Issue] chunky probably not unloading chunks

### ISSUE THREAD

**Issue by Kipura** [pop4959/Chunky#201]
So during pregeneration chunky uses up more and more ram, which might be normal,
but after I cancel or finish the pregeneration the usage won't go down. I normally sit at a
maximum of 6gb of ram that's used by the server. I pregenerated for like 10 mins and
now it's at 12.8gb and won't go down even after another 10 mins of waiting.

Edit: just for information i'm playing All of Fabric 5

**Comment by pop4959** [comment]
Usually an issue with other installed mods, I see you're on Discord so let's continue to troubleshoot there.
