### ISSUE TITLE
Feature request: Adding a delete command

### ISSUE THREAD

**Issue by Taybosquee** [pop4959/Chunky#202]
Making another command that works as the reverse of Trim. Currently, trim deletes all the chunks *outside* the selection. This new command would delete all chunks *inside* the selection instead. This could be used to amputate specific areas of a map and allow them to be regenerated naturally.

**Comment by Taybosquee** [comment]
Realistically, this could be implemented with issue #157. They are not the same thing, but that request is potentially another way to achieve the same effect depending on how it's done.

**Comment by pop4959** [comment]
I'm not quite sure if I understand the problem, is it currently not possible to upgrade the world? Does your world have some complex geometry or are you just trying to load all existing chunks?

If you could explain your specific situation that may give some needed context to this.

**Comment by Taybosquee** [comment]
Upgrading is possible, but the intent is to essentially un-fill to allow the chunks that players aren't using to regenerate with the new underground features. 
Think setting Chunky's radius to some really small number and running the trim command. Normally *everything* outside the radius would be deleted and naturally regenerated by the game when next visited. This suggestion is about making it possible to define regions or chunks that wouldn't be deleted by trim.


A few possible alternative features/methods that could also do this and may be more practical from a coding standpoint:

1. Making Chunky be able to run its normal functionality on existing chunks, making them regenerate (As in deleting all the chunks in the zone Chunky has selected and making them generate again as if there were no chunks there when Chunky does its map filling (If that's possible to do).

2. Making another command that works as the reverse of Trim. Currently, trim deletes all the chunks *outside* the selection. This new command would delete all chunks *inside* the selection instead.

**Comment by Taybosquee** [comment]
I just edited the original suggestion with 2 from the above. After re-thinking this, that seems like a much more logical approach to deleting areas without trimming everything.
Sorry for the confusion.

**Comment by pop4959** [comment]
Ah okay. 1) isn't easy, and I think it runs into the same problems as well as just deleting and then re-running a fill. 2) is basically the same as #195.

Though, in this case, would it not just be better outright to use an external tool like [mcaselector](https://github.com/Querz/mcaselector) to visually select the chunks you wish to delete, and then re-generate them using chunky?

Or maybe a command that just trims areas that haven't been explored by players. That is possible, and mcaselector also has an option to select based on player activity in chunks. It's something I have been considering for chunky.

**Comment by Taybosquee** [comment]
I was not aware such a tool existed. I shall do just as you suggested, and you have my thanks. 
Chunky and World Border before it were the only things I knew of for doing anything close to these kinds of mass chunk operations, hence the suggestion. I of course knew of actual map editors like Amulet, but they are not suited to this.

**Comment by pop4959** [comment]
Alright, glad to hear. It's always best to use the best tool for the job.

In this case I think mcaselector is definitely the better choice, given the amount of precision you are looking for which is not really something that can be easily done via a plugin. 😄 

And thanks for closing. The reverse-trim functionality is already on my radar, so hope to have that done eventually such that it is still possible to use chunky for cropping out rough areas. Plus potentially a way to trim based on activity automatically as mentioned (but that's a stretch goal, as it isn't quite as easy to do, at least the way I'd like to do it).
