### ISSUE TITLE
Feature Request: Add Placeholder

### ISSUE THREAD

**Issue by WaxenSs** [pop4959/Chunky#203]
Add a Placeholder to show whether chunky pregenere or not

**Comment by pop4959** [comment]
You can already check if chunky is running via the Placeholder API expansion.

They are available here through eCloud:
Chunky: [https://api.extendedclip.com/expansions/chunky/](https://api.extendedclip.com/expansions/chunky/)
ChunkyBorder: [https://api.extendedclip.com/expansions/chunkyborder/](https://api.extendedclip.com/expansions/chunkyborder/)
