### ISSUE TITLE
Fabric release on Modrinth is not for Fabric

### ISSUE THREAD

**Issue by mpfaff** [pop4959/Chunky#209]
The file uploaded for version 1.2.217 for Fabric on Modrinth is not compatible with Fabric. The one on curseforge works fine.

[This](https://modrinth.com/mod/chunky/version/1.2.217-fabric) is the specific release (I haven't checked others).

**Comment by pop4959** [comment]
Hm... that's seriously concerning.

The release has been out for 2 months already and it was 100% correct when I uploaded it. Looks like this may be a bug on Modrinth's side. Every download is currently serving the Sponge version of the mod.

Interestingly, the file size listed on each appears to be correctly listed for the version that was originally uploaded, so the files must exist on the backend still, which is good to know.

Leaving this issue open to track. I'll reach out to the Modrinth team so they can investigate.

**Comment by pop4959** [comment]
I received a response earlier, and it looks like the issue behind this was fixed but didn't retroactively apply to artifacts uploaded during the time it was broken. I've re-uploaded everything and it looks to be working again. Let me know if you have any other issues with it!
