### ISSUE TITLE
Chunky border asks for later version that doesn't exist in curseforge

### ISSUE THREAD

**Issue by JannekeJairia** [pop4959/Chunky#219]
I installed the 1.18.2 version of chunky and chunky border. However it doesn't work. 

Chunky border needs version 1.2.88 of chunky, but that doesn't exist on curseforge. 
Am I missing something? 
see the copy paste of the error in the txt below
[chunkyborder.txt](https://github.com/pop4959/Chunky/files/9691172/chunkyborder.txt)

**Comment by pop4959** [comment]
Here is my response to the same question on the Chunky Border repository:

> This was an oversight, I was working on the port of ChunkyBorder to Fabric during 1.18, and it was only released after 1.19 came out. The builds of Chunky that are compatible with ChunkyBorder for 1.18 are not posted to CurseForge.
>
> At this time I do not plan on making another release build for 1.18. The development builds that currently have support for ChunkyBorder should work just fine, but current release builds target 1.19. I just don't really have the spare time to backport all changes made in newer versions of Minecraft to older versions.

Basically, Chunky Border for 1.18 was supported for an extremely short amount of time. I would recommend updating to 1.19, but if you can't, you can still download the old development build to get it to work. These can be found through CodeMC (linked on the project page). If you're still confused, please join the chunky support channel on our [Discord server](https://discord.gg/PHpuzZS)!

**Comment by JannekeJairia** [comment]
Thanks, Looked up the one through CodeMC and that's working perfectly :)

**Comment by pop4959** [comment]
Awesome, glad to hear 😃
