### ISSUE TITLE
Use RegisterCommandsEvent to register forge commands

### ISSUE THREAD

**Issue by JustRed23** [pop4959/Chunky#228]
I see that you are using the normal dispatcher to register your commands, please use forge's RegisterCommandsEvent to register them instead

**Comment by pop4959** [comment]
Thanks for the tip, looks like this should potentially reduce conflicts with other mods (though, over the last year or two, I have yet to see a report indicating that to be an issue, so it should be rare). If you've encountered any, let me know. The change will be included in a future release, but for now you can obtain a build from our CI [here](https://ci.codemc.io/job/pop4959/job/Chunky/) or through [Github Actions](https://github.com/pop4959/Chunky/actions).
