### ISSUE TITLE
Please add a speed setting, or add a setting to load a capped amount of chunks per second. It keeps crashing my server.

### ISSUE THREAD

**Issue by 42Willow** [pop4959/Chunky#232]

**Comment by 42Willow** [comment]
I know this is mentioned already in #4 but I can't even run this with no players online... Yes, I've got 2gb of random access memory.

**Comment by pop4959** [comment]
Chunky should not cause your server to crash. In any case, please join the #chunky channel on our [Discord server](https://discord.gg/ZwVJukcNQG) for help troubleshooting. We should be able to help you there. If there is an actual bug or issue to fix we can re-open this.

**Comment by 42Willow** [comment]
> Chunky should not cause your server to crash. In any case, please join the #chunky channel on our [Discord server](https://discord.gg/ZwVJukcNQG) for help troubleshooting. We should be able to help you there. If there is an actual bug or issue to fix we can re-open this.

Unfortunately I do not use discord, but I have the server crash report and logs - the server crashes when loading excessive numbers of chunks quickly. I think it this would be a useful option for low-end servers.

**Comment by pop4959** [comment]
Feel free to post them here, I can still help but it will be slower than through chat.

Chunky runs fine even on a raspberry pi (though at a speed of maybe only 1-2 chunks per second), and is designed to scale with the server's performance.

I can almost guarantee you that slowing things down won't accomplish anything, but if necessary we can try that. Before anything else, please post logs and/or crash reports as applicable so I can take a look.

**Comment by 42Willow** [comment]
> Feel free to post them here, I can still help but it will be slower than through chat.
> 
> Chunky runs fine even on a raspberry pi (though at a speed of maybe only 1-2 chunks per second), and is designed to scale with the server's performance.
> 
> I can almost guarantee you that slowing things down won't accomplish anything, but if necessary we can try that. Before anything else, please post logs and/or crash reports as applicable so I can take a look.

Thank you for the quick reply, I will attach the crash reports :)
[crash-2022-12-14_06.49.07-server.txt](https://github.com/pop4959/Chunky/files/10225083/crash-2022-12-14_06.49.07-server.txt)
This happens consistently after a few seconds of pregenerating chunks. I am running the mod on a Minehut server with 2gb of RAM alongside other world generation mods (it crashes normally too, when loading many new chunks - which is why I want to pregenerate them)

**Comment by pop4959** [comment]
The crash log contains a watchdog error, which means that the server took too long to tick. You can try increasing "max tick time" in your server properties as that may help. If not, it's likely that one of your mods or something else is causing your server to crash, it's fairly difficult to tell exactly what from the crash log you've posted. Oftentimes, it can be some world gen mod, or even something seemingly unrelated, but you won't know for sure unless you've tested without them. The fact that it crashes normally does indicate that something is wrong here though -- and definitely unrelated to chunky. If you can fix whatever is causing your server to crash here you should be able to pregen just fine.

**Comment by 42Willow** [comment]
Yes the worldgen mod increases the chunk loading time,which consequentially decreases the tick speed, which then crashes the serve. This is why I was looking for a chunk preloader in the first place, and unfortunately I do not have access to the server properties file as it is locked by Minehut. Thank you for your help.

**Comment by pop4959** [comment]
I'm familiar with Minehut, you can access max tick time from the settings panel in the dashboard. So you should be able to change that. Keep in mind that chunk generation in general is async, and so this does not cause long tick times to begin with -- which is why chunky is pretty much wholly uninvolved in this issue occurring. I hope that makes sense. I do generally wish I could help more with this but I think at this point it seems clear that the issue lies with server configuration and/or other mods at play here. Definitely keep digging and I'm sure you will find a fix for this.

**Comment by 42Willow** [comment]
Oh thank you so much, I didn't realise there was a max tick time setting on minehut. I'll try that now and let you know.

**Comment by pop4959** [comment]
Absolutely no problem, give it a try and see if that helps at all. 👍

**Comment by 42Willow** [comment]
yep! I disabled watchdog by setting it to -1 and it works perfectly now! It still crashes sometimes when loading a very large area (runs out of ram) but it's fine for a few hundred blocks.

**Comment by pop4959** [comment]
Yep there you go. I had a hunch that might just do it. If you can, I recommend going through the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) and optimizing your server further if possible. Note that while 2GB certainly works, usually (and especially with large modpacks) 4GB+ is recommended to avoid the server running out of memory quickly.
