### ISSUE TITLE
It did'nt work!

### ISSUE THREAD

**Issue by chinabestcountry** [pop4959/Chunky#234]
I put the jar into my plugin folder and then restart my server but nothing happened!
There no any log or error but just nothing happened.But when i used /plugin load Chunky it told me that i can only load it by restarting server.Here's info of my server:
Paper 1.16.5
Can someone help me? Plz
:)

**Comment by pop4959** [comment]
Make sure you download the correct version for your server. For Paper 1.16.5 that would be Chunky 1.2.217. The latest versions require Java 17 or above to be installed. Also make sure you are not using a plugin manager to install the plugin, it's best to just restart the server normally.

If you still have any questions post in the #chunky channel on our [Discord server](https://discord.gg/ZwVJukcNQG) and we can better help you there.

**Comment by chinabestcountry** [comment]
but paper1.16.5 didn't support java 17+!

**Comment by pop4959** [comment]
Yes that's why you want the older version, 1.2.217, which is compatible with Java 8+.

The latest versions (1.3.0+) require Java 17.
