### ISSUE TITLE
Feature request: keep chunks loaded

### ISSUE THREAD

**Issue by masmc05** [pop4959/Chunky#237]
Add a configuration that sets a time after the chunk was generated for it to be loaded (defaulting to 0, meaning disabled)

This should help with some other parts of lags with chunks, as now, we noticed that the lava in new nether chunks gets a significant part of lags of our server, and pregenerated chunks with chunky don't have the lava processed, so we start to have millions of lava that wasn't preprocessed

**Comment by masmc05** [comment]
![image](https://user-images.githubusercontent.com/63639746/215160805-87781262-2b8a-4529-8863-77eb5bcdc616.png)
that's what's happening on our server, even if the chunks were pregenerated

**Comment by pop4959** [comment]
Sorry I have seen this but forgot to reply; I will look into this to see if anything further can be done, however post processing (fluids, block physics, etc) are not technically part of the chunk generation process so this is pretty normal.

**Comment by masmc05** [comment]
> Sorry I have seen this but forgot to reply; I will look into this to see if anything further can be done, however post processing (fluids, block physics, etc) are not technically part of the chunk generation process so this is pretty normal.

with leaf's patch we don't see right now a big difference between pregenerated and not pregenerated world, however this part that is after generation still creates lots of lags
