### ISSUE TITLE
Trim command not working 

### ISSUE THREAD

**Issue by Chungus-Epic** [pop4959/Chunky#238]
I installed Chunky 1.3.53 and Chunkyborder 1.1.43 using CurseForge for 1.19.3 and the trim command doesn't seem to work. All the chunks outside the region I specified do not disappear and I can still interact with them like normal. Also in Chunkyborder, I can pass through and teleport outisde of the worldborders I set with no resistance. Am I missing some commands or something? How do I make the trim feature work properly and the world borders impassable?

**Comment by pop4959** [comment]
Trim can be a bit confusing. Have you read the section about trim on the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ#trim-isnt-working)? If you are currently loading these chunks they will not be deleted.

Additionally keep in mind chunks deleted by trim will be re-generated again if you visit the area they are in. If you don't want to generate them again do not go back to the area you trimmed. Set up a world border to prevent players from accessing those regions.

If you need further assistance with this please join the chunky support channel on our [Discord server](https://discord.gg/ZwVJukcNQG).

**Comment by Chungus-Epic** [comment]
Ah ok that makes sense, thank you. Still, like I said, the world border isn't 'hard', I can literally walk right through it. Is there a way I can make it so I can't bypass the world border? Also to clarify I'm playing on a singleplayer world.

**Comment by pop4959** [comment]
Vanilla world border supports hard collision so you can use that if it's an option.

For chunky border & especially non-square regions, there is no hard collision support. You can change the check interval in the configuration from 20 ticks to 1 tick which makes it as close as possible to being a hard border (it will teleport players back within 1 tick of passing). Alternatively, pad your border with a few chunks if the only concern is a web map like dynmap being pretty (or better: set a visibility limit so the areas past the border aren't rendered on your map).
