### ISSUE TITLE
Garbage collector lag

### ISSUE THREAD

**Issue by Gryem** [pop4959/Chunky#241]
I installed this because i got chunk lags and it fixed that. Now i am getting huge garbage collector lag spikes and i have no idea why

**Comment by pop4959** [comment]
This is not the place to ask for unrelated server performance help. I recommend asking in the [Paper Discord](https://discord.com/invite/papermc) (if you're using Paper) in another hosting / server discussion forum instead for your particular setup.

If your question is specifically about Chunky, feel free to join our [Discord server](https://discord.gg/ZwVJukcNQG) and ask in the the support channel.

If you have a bug to report, you can open another issue here on Github with relevant details and reproduction steps. Keep in mind that memory / garbage collector issues usually have to do with your hardware or server configuration and are usually not reportable bugs.
