### ISSUE TITLE
Don't know how to turn object into a Component

### ISSUE THREAD

**Issue by AquaLawng** [pop4959/Chunky#243]
While trying to fix a bug where the progress bar was stuck at the top of the screen, after the operation was complete, I did the following:

Tried restarting Minecraft, restarting the server, and uninstalling all files related to Chunky from the server folder, and the bar is still stuck there. I then tried adding Chunky back to the server, with new and original config files, and now nothing works. Now, every time i try a Chunky command, I get disconnected from the server and receive:

"Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"comp_737":"chunky radius <radius> - Set the radius"} into a Component"
![Screenshot 2023-02-20 095814](https://user-images.githubusercontent.com/61892317/220140218-809e9d0b-0d32-47f5-996a-454f0171e69c.png)

If I run the commands from the servers console, the server crashes.
[crash-2023-02-20_09.29.46-server.txt](https://github.com/pop4959/Chunky/files/10785490/crash-2023-02-20_09.29.46-server.txt)

**Comment by pop4959** [comment]
Thanks; as mentioned in the previous issue if you are able to I would hop on the Discord server so we can try a few things to try to get this resolved.

**Comment by AquaLawng** [comment]
Already there, same username as here

**Comment by pop4959** [comment]
Turns out to be an incompatible version issue, nothing to fix here.
