### ISSUE TITLE
TPS goes way down with Lithium

### ISSUE THREAD

**Issue by chcknlvr** [pop4959/Chunky#244]
![image](https://user-images.githubusercontent.com/77564494/221082539-db4f8328-d517-4178-aeb1-b503bf670f39.png)
![image](https://user-images.githubusercontent.com/77564494/221082594-a0794329-4d18-461f-a4b1-9c95b0a972f7.png)
I was pregenerating the end on my 1.19.3 modded fabric server, and I noticed that it crashes after a while. Looking into the logs, it looks like what happened is that a tick took 60 seconds so the server shut down. When looking at spark, I saw that Lithium was accounting for much of the tick time. I also noticed that from the usual 140 chunks per second, it drops until that 60 second tick occurs.
![image](https://user-images.githubusercontent.com/77564494/221083149-e7c41048-3f10-4409-bb03-d6ef9d622c5c.png)

**Comment by pop4959** [comment]
Thanks for the report.

Can you share your spark link? That would be more helpful than choice screenshots. There isn't much useful information here besides seeing that something is lagging.

If you'd like, also join the [Discord server](https://discord.gg/ZwVJukcNQG) and find the chunky support channel for help troubleshooting.

**Comment by chcknlvr** [comment]
https://spark.lucko.me/6puerPRi13

**Comment by chcknlvr** [comment]
[2023-02-23-2.log.gz](https://github.com/pop4959/Chunky/files/10828697/2023-02-23-2.log.gz)
[crash-2023-02-23_20.46.51-server.txt](https://github.com/pop4959/Chunky/files/10828699/crash-2023-02-23_20.46.51-server.txt)

**Comment by pop4959** [comment]
Your spark expired, so I'm not able to look at it. The main thing that stick out to me here is Dynmap, etc, seemingly running in the background while you're pre-generating. I recommend disabling that until you're done.

If you still need help troubleshooting this please join the chunky support channel in our [Discord server](https://discord.gg/ZwVJukcNQG).
