### ISSUE TITLE
Why does the ETA generation world take so long while the computer CPU and disk hardly work

### ISSUE THREAD

**Issue by sherholm** [pop4959/Chunky#249]
![image](https://user-images.githubusercontent.com/127023360/222957294-39be4e11-c936-4661-9ddd-88b9c2cd8ea0.png)
![image](https://user-images.githubusercontent.com/127023360/222957330-f8dec8d8-0217-4f6e-ab01-cb9a43e5760d.png)
Hello author, I have always loved this plugin. However, I don't know why cps will be higher and lower after a while, resulting in very slow generation. I have been generating for two days in a row.

**Comment by pop4959** [comment]
It is normal for pre-generation to take many hours, or even days. Minecraft has many bottlenecks in how it generates worlds, and so it will not normally use your entire CPU to do so.

If you want tips on how to improve generation rate, take a look at the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ).

If you have further questions, please join the chunky support channel on our [Discord server](https://discord.gg/ZwVJukcNQG).
