### ISSUE TITLE
Feature request: Trim chunks that players haven't stayed in for long.

### ISSUE THREAD

**Issue by Pantera07** [pop4959/Chunky#251]
I propose adding a function that allows trimming of chunks that players haven't stayed in for long.
This would be useful for deleting and regenerating unnecessary chunks after updating the server version, allowing players to experience new biomes.

**Comment by pop4959** [comment]
Trim using inhabited time. This was added in 66179d4a451ff0b32127ddd6af3cb6cd9d1a257b. You can find documentation on the command arguments here: https://github.com/pop4959/Chunky/wiki/Commands#trim

Note that this isn't currently a released version, you will need to download it from CodeMC or Github Actions.
