### ISSUE TITLE
[Support] Generating for dimension

### ISSUE THREAD

**Issue by tyler72us** [pop4959/Chunky#255]
Is it possible to get chucky to load different dimensions (the End, or from mod like blue skies) instead of just the overworld?

**Comment by pop4959** [comment]
Yes, you use the world command to change the dimension. You can use any dimension from vanilla or one added from mods.

Read more [here](https://github.com/pop4959/Chunky/wiki/Pregeneration) and join Discord if you have any other questions.

**Comment by pop4959** [comment]
If you're using the DawnCraft mod pack, the added dimensions are:
```
blue_skies:everbright
blue_skies:everdawn
simple_mobs_distant_land
```

This is in addition to the normal minecraft dimensions:
```
overworld
the_nether
the_end
```

I hope that helps!

**Comment by tyler72us** [comment]
That's very helpful. Thanks!  How do I find those names?  I have a mod pack
that has blue skies but also has the twilight forest.

**Comment by pop4959** [comment]
The dimension id is usually the mod name, `:` then the dimension name.

Usually either look at the mod's documentation, or try to figure it out yourself by looking at the world folders (there is usually a folder in your level with the mod name, and under that, the dimension name).

Chunky will also automatically suggest any installed dimensions to you with the `chunky world` command when in-game or using a better console mod for dedicated servers.

**Comment by tyler72us** [comment]
Awesome, thank you so much!
