### ISSUE TITLE
Translations to cs are not correct

### ISSUE THREAD

**Issue by FatildaIV** [pop4959/Chunky#258]
While I appreciate the approach of [automatically translating messages](https://github.com/pop4959/Chunky/blob/96bb1ea7e2eed695f6389bf1ab4b382b706126e1/common/src/test/java/org/popcraft/chunky/util/TranslatorTest.java) to different languages, some sentences are not translated correctly because the use of variables does not give the translator a clear context. Example:

Original message: _Task running for {world}. Processed: {amount} chunks ({percentage}), ETA: {remaining}, Rate: {rate} cps, Current: {chunk}_
> Example usage: Task running for world. Processed: 3397254 chunks (80.92%), ETA: 51:19:04, Rate: 4.3 cps, Current: 922, 317

Translation to cs: _Úkol běží po dobu {world}. Zpracováno: {amount} chunků ({percentage}), ETA: {remaining}, Hodnota: {rate} cps, Aktuální: {chunk}_

Translated back to en: _Task has been running for {world}. Processed: {amount} chunks ({percentage}), ETA: {remaining}, Value: {rate} cps, Current: {chunk}_
> Although translation is mostly accurate, the Czech language use different prepositions for time and subject of the sentence. In this example "_Task running for {world}_" can translate to:
> - _Úkol běží pro {world}_, where {world} is the subject of the sentence
> 
> or
> - _Úkol běží po dobu {world}_, where {world} is the adverb of time

The used translator cannot determine the context of the sentence, so it chooses the wrong translation, which is then used in the plugin message. Another example can be seen in the word "_rate_", which can be translated to "hodnota" (value) or "rychlost" ("rate" - speed).

My recommendation is to hardcode the existing translations (even if generated by the existing translator) to the plugin repository (since languages do not evolve fast enough to require translation at every compilation), and in case of errors, native speakers can post a pull request to fix the translation errors made by the artificial traslator.

**Comment by pop4959** [comment]
Chunky uses no automated / machine translations. The test that you are referring to *only* parses the strings to ensure that they do not produce errors when filled with appropriate placeholders.

To correct mistranslated text in the plugin, please use [Crowdin](https://crowdin.com/project/chunky).

I can also make you a proofreader if you like, which gives you the ability to ensure that accurate translations are not later replaced with less accurate ones (since anyone can contribute at any time).
