### ISSUE TITLE
`the_nether` world specifier doesn't work

### ISSUE THREAD

**Issue by splurf** [pop4959/Chunky#261]
### Specifying with `world_nether` works but `the_nether` doesn't.

![image](https://user-images.githubusercontent.com/62043858/232826090-76361b0d-a986-4b48-afcd-1d0743f4d7bf.png)

When trying to specify the world selection to the nether, `the_nether` specifier does not work.

The *Pregeneration* wiki states that you can use `world_nether` or `the_nether` but only `world_nether` works. Maybe this was intentional and the wiki never got an update.

![image](https://user-images.githubusercontent.com/62043858/232827856-298354af-84c5-4276-8d5a-c2e9331dd4f4.png)

Edit:

I also tried the other *optional* specifiers (`overworld` and `the_end`) and those didn't work either.

**Comment by pop4959** [comment]
Hi, the wiki looks correct. Read the note above the given world list, you will see that the name depends on the version of chunky you have installed.

In your case, you probably have the Bukkit platform version installed and so only the Bukkit world names will work. On the modded platforms such as Fabric and Forge the vanilla dimension ids (the ones that aren't working for you) work.
