### ISSUE TITLE
Using an CSV file for custom patterns.

### ISSUE THREAD

**Issue by RatDotRaw** [pop4959/Chunky#263]
I am trying to use/make a custom pattern for chunky, but I am unable to figure out how.
I have read the documentation about patterns and found that I need to use an .CSV for this, but the documentation doesn't tell how this file should be structured and where to be places (I assume in the Chunky folder inside plugins). 
An example file or table on the wiki page would help me to figure out how to use this custom pattern.

My next "problem" is more of a suggestion, but if you type "/chunky pattern [assume I typed a valid or invalid pattern here]", the plugin always responds with an info text on how to use the command. 
It would be nice if it gave a confirmation if the pattern was changed successfully.

**Comment by pop4959** [comment]
The csv file goes in the plugin folder and include columns for chunk x and chunk z coordinates to visit.

E.g.

```
0,0
```

Then select the csv pattern with `chunky pattern csv <name>`.

It will tell you that it has selected the pattern of everything has been done correctly.
