### ISSUE TITLE
Server is restarting after some time when I will load the chunks of the world

### ISSUE THREAD

**Issue by Endphoenix** [pop4959/Chunky#27]
When I try to load all the chunks, at some point there will always be a message that the server is overloaded. And that with 3GB RAM! After that, the server restarts again and again. However, I found this here in the "restart.log".

2020-08-11 02:29:34 Server restart requested (NITRAPI)
Tue 11 Aug 2020 02:29:50 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
Wed, 12 Aug 2020 14:47:58 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Wed, 12 Aug 2020 14:48:01 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Wed 12 Aug 2020 02:48:10 PM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-13 02:29:23 Server restart requested (NITRAPI)
Thu 13 Aug 2020 02:29:28 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-14 02:29:17 Server restart requested (NITRAPI)
Fri 14 Aug 2020 02:29:48 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-15 02:29:16 Server restart requested (NITRAPI)
Sat 15 Aug 2020 02:29:19 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-16 02:29:11 Server restart requested (NITRAPI)
Sun 16 Aug 2020 02:29:47 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-17 02:29:33 Server restart requested (NITRAPI)
Mon 17 Aug 2020 02:29:40 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-18 02:29:23 Server restart requested (NITRAPI)
Tue 18 Aug 2020 02:29:53 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-19 02:29:10 Server restart requested (NITRAPI)
Wed 19 Aug 2020 02:29:41 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-20 02:29:06 Server restart requested (NITRAPI)
Thu 20 Aug 2020 02:29:33 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-21 02:29:33 Server restart requested (NITRAPI)
Fri 21 Aug 2020 02:29:36 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-22 02:29:23 Server restart requested (NITRAPI)
Sat 22 Aug 2020 02:29:49 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-23 02:29:11 Server restart requested (NITRAPI)
Sun 23 Aug 2020 02:29:15 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-24 02:29:20 Server restart requested (NITRAPI)
Mon 24 Aug 2020 02:29:36 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-25 02:29:27 Server restart requested (NITRAPI)
Tue 25 Aug 2020 02:29:57 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-26 02:29:27 Server restart requested (NITRAPI)
Wed 26 Aug 2020 02:29:50 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-27 02:29:31 Server restart requested (NITRAPI)
Thu 27 Aug 2020 02:29:45 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-28 02:30:49 Server restart requested (NITRAPI)
Fri 28 Aug 2020 02:31:24 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-29 02:29:35 Server restart requested (NITRAPI)
Sat 29 Aug 2020 02:29:51 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-30 02:29:22 Server restart requested (NITRAPI)
Sun 30 Aug 2020 02:29:32 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
Sun, 30 Aug 2020 16:24:06 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Sun 30 Aug 2020 04:24:15 PM UTC mcrbuk Server restart via Restart-file or Webinterface requested
Sun, 30 Aug 2020 20:14:35 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Sun 30 Aug 2020 08:15:05 PM UTC mcrbuk Server restart via Restart-file or Webinterface requested
2020-08-31 02:29:17 Server restart requested (NITRAPI)
Mon 31 Aug 2020 02:29:56 AM UTC mcrbuk Server restart via Restart-file or Webinterface requested
Mon, 31 Aug 2020 16:31:44 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Mon, 31 Aug 2020 16:31:46 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Mon 31 Aug 2020 04:31:48 PM UTC mcrbuk Server restart via Restart-file or Webinterface requested
Mon, 31 Aug 2020 16:38:32 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Mon, 31 Aug 2020 16:38:35 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Mon 31 Aug 2020 04:38:52 PM UTC mcrbuk Server restart via Restart-file or Webinterface requested
Mon, 31 Aug 2020 17:10:02 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Mon, 31 Aug 2020 17:10:04 +0000 100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver. (SIGTERM)
Mon 31 Aug 2020 05:10:30 PM UTC mcrbuk Server restart via Restart-file or Webinterface requested

Maybe that helps you.

And should I perhaps set "warn-on-overload: true" to false in "bukkit.yml"? I have not changed anything there. This is standard.

Server Version: Spigot 1.14.4
Chunky Version: Chunky-1.1.7 #

**Comment by Endphoenix** [comment]
I use "/chunky worldborder" and then "/chunky start". When the Server is restarting, "/chunky continue" don't work.

**Comment by pop4959** [comment]
This isn't a bug in Chunky. See the message from your log:
"100% CPU usage detected. Mostly caused by server crash. Restarting Gameserver."

Your host is shutting down your server. This might be indirectly related to world generation, but it is definitely not Chunky's fault.  You need to either get another host or use a slower chunk generation plugin like [WorldBorder](https://www.spigotmc.org/resources/worldborder-pures-fork.81706/). I would recommend the better host.
