### ISSUE TITLE
1.19.2 forge crash while trying to pregenerate chunks

### ISSUE THREAD

**Issue by FearAK** [pop4959/Chunky#271]
Left my pc to pre generate a circle radius from 0 0 10000 out and i came back to it having crashed after a while.

https://hastebin.com/share/uxasocowoj.bash

**Comment by pop4959** [comment]
You have an illegal state during world gen. Likely another mod trying to access that random source at the same time as vanilla.

I don't really have any specific recommendations here besides removing mods until you find the culprit.

If you have any other questions or need help troubleshooting, please join the [Discord server](https://discord.gg/ZwVJukcNQG).
