### ISSUE TITLE
Expanding World Border

### ISSUE THREAD

**Issue by ThomasGW120** [pop4959/Chunky#272]
Hello Author. I set the world border to 30000 blocks wide for now and I pre-generated chunks. If I'd like to expand the border to 50000 blocks wide, when I start pre-generating, will Chunky load the chunks that have been loaded before?

**Comment by pop4959** [comment]
No, as mentioned on the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) it will not load them again, but it will scan over the chunks quickly to determine if they were already generated or not. This is quick, but may still take a few minutes.
