### ISSUE TITLE
Multiple tasks in same dimension

### ISSUE THREAD

**Issue by filips123** [pop4959/Chunky#280]
Currently, it does not seem to be possible to run multiple tasks in the same dimension at the same time. I would like to pregenerate multiple sections around multiple centers (for example, 2000 radius around 2000, 2000; and 1000 radius around -7000, 0). When trying to do this, I get "task already running" error.

There should be support for doing this, probably by allowing to run multiple `chunky start` commands sequentially. There might need to be additional handling in case two sections overlap. In case that would be too hard to implement, adding the ability to queue tasks after one is finished would also be good.

**Comment by pop4959** [comment]
Running multiple simultaneously is intentionally not supported, as world generation runs per world, so running multiple tasks in parallel for the same world makes no sense (none or potentially negative performance impact).

A queue would be fine quality of life feature though. I'll look into that when I find time.

**Comment by pop4959** [comment]
Okay so while this would be considered a fairly trivial affair using the [Chunky API](https://github.com/pop4959/Chunky/wiki/Developer-API), setting up a system for this in the plugin itself is a bit more effort than I'd like to invest in a feature like this at the moment. Not to say that this can never / will never exist, and if a reasonable enough PR landed on my doorstep I would give it another thought, but for now, I would strongly recommend using the API, especially given that you will be able to easily, and very precisely, get the kind of task scheduling you want for your server.

As usual, I am around on the [Discord server](https://discord.gg/ZwVJukcNQG) if you would like to discuss further, have any ideas, or need assistance while setting up a simple addon that does this. I am also aware of someone who was already thinking of making an addon for this and if that becomes publicly available I will try to remember to link it in this thread as well.
