### ISSUE TITLE
Give the ability to increase the speed of generation

### ISSUE THREAD

**Issue by JuraRusan** [pop4959/Chunky#281]
I have been using this plugin for a very long time and sometimes I have to wait a lot of time to generate 10x10k worlds for several hours. I would like to suggest that in the plugin settings it would be possible to adjust the generation speed, since in any case I always generate a map without players, and it would be possible to have a higher speed than now. Chunk generation has been observed to take up approximately 10-15% of CPU resources, although it has a very high potential (r9 7950x). If the plugin had a speed setting function, it would be very cool!
Thank you!
![image](https://github.com/pop4959/Chunky/assets/76946109/b9425970-1d41-44c3-91b2-40ccc045da52)

p.s. 
I know there is a "Fast Chunk Pregenerator" but I don't really like it..

**Comment by pop4959** [comment]
There are no options that need to be changed plugin-side, it runs as fast as it can already. See the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) for more information.

On a dedicated 7950x you should be able to get much higher than 80-90 cps (I get a few hundred on mine) if you configure things correctly in the server.
