### ISSUE TITLE
[Forge] Incompatibility with 1.18 Magma, due to #228

### ISSUE THREAD

**Issue by C0D3-M4513R** [pop4959/Chunky#283]
#228
Chunky commands are autocompleted on Magma, but executing them does not work.
Could you use the proper Forge Command register event for 1.18?

**Comment by pop4959** [comment]
This event is already being used to register Forge commands. For an older version, yes, but I do not have time to backport every change to every old Minecraft version. In addition, Magma (as well as any other forks of Forge) are not tested and as a result any bugs with these forks should ideally be reported to them, and not here. I don't guarantee any compatibility with them.

If you do still want to backport the change yourself for your own use, you are of course welcome to do so.
