### ISSUE TITLE
Allow for throttled chunk generation as to not disrupt gameplay

### ISSUE THREAD

**Issue by douglasg14b** [pop4959/Chunky#287]
Allow for chunk generation to be throttled to some degree (as an option, based on chunk generation rate). This can be handy when generating large servers, while still allowing players to play.

I don't assume this to be an easy problem, to be clear. But it would be quite valuable if solved.

**Comment by pop4959** [comment]
This has been brought up and discussed numerous times, and has generally proven to be a non-issue. Chunk generation is largely off the main server thread, so you should see little to no impact on game performance itself. There is also no explicit prioritization in scheduling over player-generated chunks, and as such should not significantly affect gameplay. I would encourage you to try it out for yourself first, as most likely you will run into no problems, but if you do, please join the [Discord server](https://discord.gg/ZwVJukcNQG) for help troubleshooting and to discuss further.

**Comment by douglasg14b** [comment]
I've been running it for a while now, and expanding the map periodically. I notice that tic-lag is definitely worse when chunks are being generated and players are online. And player generated chunks are brutally slow to generated, which is a large reason for throttling Chunky as more players are on.

Maybe I should have led with that?

Essentially, I have tried it, and have been using it, and have noticed the problem :/

**Comment by pop4959** [comment]
If you are still having issues please use the Discord link above and send me a spark profile of your server as well as any other relevant information so I can better evaluate this and help you.

**Comment by pop4959** [comment]
Yes as mentioned previously, there generally aren't any issues requiring any sort of throttling on the server. Starving your system of memory will definitely cause issues, I think I would have come to a similar conclusion.

For any future concerns, please join the Discord server (link in earlier post, it hasn't changed), would prefer not to bump here as it emails everyone.
