### ISSUE TITLE
World Parameter Issue - Nether

### ISSUE THREAD

**Issue by cjh15hub** [pop4959/Chunky#296]
If you set the world to the nether, and run start, it says generating for the overworld. I don't know if it is a display error, or if the command doesn't work.

v 1.3.92 Chunky (Forge)

**Comment by pop4959** [comment]
Seems to work on my end. Make sure you haven't disabled the nether, and are using the correct dimension ID (e.g. "nether" is not valid, "the_nether" is).

Visit us on [Discord](https://discord.gg/ZwVJukcNQG) if for some reason you still have trouble.
