### ISSUE TITLE
Do chunky work on 1.20.2 - 1.20.4?

### ISSUE THREAD

**Issue by editon96** [pop4959/Chunky#304]
I want to update my Server and ask this myself.
I test it ofcorse then but right now I get Informations to all my Plugins that I use and by Chunky I cant finde if it support 1.20.2 only that is suporting 1.20...

**Comment by pop4959** [comment]
Yep, generally should continue working just fine, since we only use API. That said, Paper hasn't released yet so can't fully test yet.
