### ISSUE TITLE
(idea) Make the player invicible while the chunk are pre-generating once you load a world.

### ISSUE THREAD

**Issue by Geming400** [pop4959/Chunky#306]
It would be nice to have an invicibility buff when the chunk while the chunks are loading to prevent you for dying when you can't move.
I don't think it's possible to do that, so i'm requesting this feature. Thanks!

**Comment by pop4959** [comment]
I'm not really too sure what the utility of this would be, considering pre-generation doesn't really impact gameplay at all.

If you would like this, I would recommend using another mod or plugin that grants invulnerability. Either way I don't think it would make sense to include here.
