### ISSUE TITLE
chunky don t use more than 2 core and only at 30%

### ISSUE THREAD

**Issue by SPglouglou** [pop4959/Chunky#310]
how do i make chunky use more thread?
i have an i9 13900kf but it don t go higher than 15% and only 4 core is use at no more than 20%

**Comment by pop4959** [comment]
This is answered on our [wiki](https://github.com/pop4959/Chunky/wiki/FAQ) and you can also join the [Discord server](https://discord.gg/ZwVJukcNQG) if you have any other questions.
