### ISSUE TITLE
[Feature requests] player-pre-generate-limit

### ISSUE THREAD

**Issue by moesnow** [pop4959/Chunky#314]
```yaml
# The amount of players that is needed to pause BlueMap's render-threads.
# -> If this amount of players or more is online, bluemap will stop rendering map-updates until enough players
#    have logged off again
# Setting this to 0 or -1 will disable this feature -> bluemap will not pause rendering
# Default is -1
player-render-limit: -1
```
Is it possible to add an option similar to bluemap's player-render-limit, perhaps called player-pre-generate-limit? It should only continue running when the number of players is less than the set value, which can help avoid impacting game performance.

**Comment by pop4959** [comment]
As mentioned in many prior issues, this is better suited for add-ons (and some already exist for this). World gen shouldn't be causing a huge performance impact anyways, so 99% of the time you should not need this though.

As such, not planned.
