### ISSUE TITLE
Not generating Blue Skies Ocean chunk

### ISSUE THREAD

**Issue by Jadan1213** [pop4959/Chunky#317]
Forge: 42.2.17
MC: 1.20.1

I pregenerated the Blue skies: everbright dimension, and noticed that while most of the chunks did generate, the ocean chunks had to be generated on demand.

**Comment by pop4959** [comment]
I don't expect that this is a bug with chunky, so unless you can provide further information pointing in that direction I will be unable to look into this further. Chunky simply loads the chunks, and all generation work is done by the server (and in this case, the Blue skies mod you mentioned). There are no other reports of chunks "not generating" at the moment. It's possible that it could be as simple as not having selected the correct region or dimension while generating, or something else.

If you're still having problems with this please join our [Discord server](https://discord.gg/ZwVJukcNQG) and join the chunky support channel to troubleshoot further. I would love to be able to help you figure this out, but GitHub issues is not the best place for discussing.
