### ISSUE TITLE
Crashing while generating chunks on Minecraft 1.20.4 Fabric

### ISSUE THREAD

**Issue by Tresillo2017** [pop4959/Chunky#320]
[crash-2024-02-17_10.59.51-server.txt](https://github.com/pop4959/Chunky/files/14318384/crash-2024-02-17_10.59.51-server.txt)
# Commands used
- ``chunky radius 2000``
- ``chunky world overworld``
- ``chunky start``

# Problem
After a while, chunky suddenly stops and CPU usage drops. Nothing appears on the server console.

**Comment by pop4959** [comment]
Not a bug; this is just a watchdog crash and generally has nothing directly to do with chunky. There is a mod in your stack trace which is "MCAFabric" that appears to be doing something here during world gen but may or may not be related to the crash.

I recommend reading the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) and join our [Discord server](https://discord.gg/ZwVJukcNQG) for more help troubleshooting the issues you're having.
