### ISSUE TITLE
[Feature Request]: Optionally play audio on completion of pre-generation task

### ISSUE THREAD

**Issue by Barking3086** [pop4959/Chunky#321]
While this is more relevant to single player worlds, I tend to pre-gen in a series of squares with radius 512, each of which (for me) can take upwards of 10 minutes. During this time, I leave my PC running and go AFK. It would be great if there could be a setting that would make Chunky play a sound effect upon completing pre-generation tasks so that I wouldn't have to constantly check to see if I could start the next square pre-gen.

**Comment by pop4959** [comment]
Thank you for the suggestion! I don't plan to add this to chunky itself, but it would be a cool feature for an API addon.

By the way, the ETA should already mostly cover this, and outside of pre-generating many very small regions (which is an unusual use case for chunky, people tend to generate one big region per world), I don't see how this would be of much use normally. You can view it using `/chunky progress` if you do not see it already in the boss bar while playing single player.

As already implied above, if you are just gradually generating larger and larger squares, it might instead be a good idea to make use of the pause/continue feature with one big square instead, and check the [world size calculator](https://onlinemo.de/world) to make sure that you aren't generating too much.

Feel free to join the [Discord server](https://discord.gg/ZwVJukcNQG) if you have any other questions or want to discuss this more.
