### ISSUE TITLE
Error loading Paper plugin

### ISSUE THREAD

**Issue by wolfieboy09** [pop4959/Chunky#325]
Paper is saying that withen this plugin, `paper-plugin.yml` or `plugin.yml`, so it can't load.

Version: 1.3.138

![the screenshot](https://cdn.discordapp.com/attachments/1213869312859836417/1215033568884162700/image.png?ex=65fb4731&is=65e8d231&hm=ae18ea41d138998678085d8253c8b2f6f92212f8dec640a715e47ac62ce84dfa&)

**Comment by pop4959** [comment]
Hi, you probably downloaded the wrong version of chunky (for example, for Fabric / Forge instead of Paper).

If you believe that you downloaded the correct one and are still having problems, please join the chunky support channel on our [Discord server](https://discord.gg/ZwVJukcNQG).
