### ISSUE TITLE
After about 10 minutes, my game drops to 0 fps and crash

### ISSUE THREAD

**Issue by abp12306** [pop4959/Chunky#327]
When I try to pregenerate, whether it is radius 500 or 2000, the game breaks after a few minutes. Please I need help.
RTX 3070 TI
Ryzen 7 3800X
16GB DDR4 RAM
Im playing on version 1.20.1 Fabric, with Nvidium, Chunky and Reterraforged.

**Comment by abp12306** [comment]
Im playing on Fabric 1.20.1

**Comment by pop4959** [comment]
Hi! For help troubleshooting issues with chunky, please join our [Discord server](https://discord.gg/ZwVJukcNQG). We're definitely able to help with crashes, but these usually are not a bug in the mod.
