### ISSUE TITLE
Chunky completely stops internal server and stops pregenerating

### ISSUE THREAD

**Issue by Gerbzzz** [pop4959/Chunky#335]
On Forge 1.20.1, after somewhere between 30s-2m Chunky will completely stop pregeneration and the internal server will stop running. This does not crash the game itself but halts anything associated with server running, including saving the game and quitting to title menu and placing or destroying blocks.
My system consistently has enough free and allocated RAM for Chunky to run pregeneration and although CPU usage is near peak (as expected), nothing is indicative of a regular crash. This has happened every time I have run Chunky today, even when disabling Embeddium and custom Java Parameters. Below is a screenshot of my mods and a text file of my game logs although it contains no indication of what has happened since it just kinda... stops. 
https://paste.atlauncher.com/view/83fb7721-66bb-4cc7-ad44-31dd36cf4f84 
![javaw_bv7N7F60ZA](https://github.com/pop4959/Chunky/assets/102229362/f595c71d-aca8-4b5a-8c62-a7b217b270d5)

**Comment by pop4959** [comment]
Hi, this sounds like a server deadlock. This is usually not caused directly by chunky, but by other mods that are installed. Unless you are able to reproduce this issue without mods, I recommend joining our [Discord server](https://discord.gg/ZwVJukcNQG) and getting help with troubleshooting this in the chunky support channel. We don't do troubleshooting in Github issues as this becomes far too time consuming. Thank you!
