### ISSUE TITLE
[wiki] update FAQ w/ buried treasure map bug (`MC-218156`)

### ISSUE THREAD

**Issue by 42Willow** [pop4959/Chunky#336]
I think it would be a good idea to update the FAQ with a temporary solution to treasure map generation whilst `MC-218156` isn't patched.

https://github.com/PaperMC/Paper/discussions/10536
https://bugs.mojang.com/browse/MC-218156

Issue: Buried treasure maps not generating.

Solution:
To fix, on paper servers
```diff
  treasure-maps:
    enabled: true
    find-already-discovered:
-      loot-tables: 'default'
+      loot-tables: 'false'
      villager-trade: false
```
The buried treasure map is generated by the server searching to find an unexplored/ungenerated buried treasure. This didn't work on my server, as all chunks are already pre generated / "explored" (by Chunky)
To fix this issue, I disabled the check the server does to see if the chest has already been looted (chunk generated). This was successful.

**Comment by pop4959** [comment]
Thank you for the heads-up, wasn't aware of this one. I added a bit on it to the FAQ, please proof read and if there are any corrections needed let me know.
