### ISSUE TITLE
Chunky 1.20.6 Neoforge Crashes on Startup

### ISSUE THREAD

**Issue by ModernGamingWorld** [pop4959/Chunky#337]
[crash-2024-05-04_17.33.18-fml.txt](https://github.com/pop4959/Chunky/files/15211151/crash-2024-05-04_17.33.18-fml.txt)

**Comment by pop4959** [comment]
You're using a version of chunky that is marked compatible with 1.20.2 to 1.20.4. Have you tried updating chunky to the latest version?

**Comment by ModernGamingWorld** [comment]
![Screenshot 2024-05-04 174942](https://github.com/pop4959/Chunky/assets/75923060/f6bc809b-ea77-413e-89e1-3bcb72a97d6a)
@pop4959 According to the Launcher, I am using the current 1.20.6, so I don't know what you mean when you say I am using the wrong version.

**Comment by pop4959** [comment]
I see 1.20.2-1.20.4 on both CurseForge and Modrinth. Not sure what launcher you are using but if it's displaying something else it is incorrect. I updated it recently to not include 1.20.6 since that version is incompatible due to changes in NeoForge.

Try downloading the Chunky 1.4.x release from GitHub Actions or CodeMC repository.

**Comment by ModernGamingWorld** [comment]
so something must be bugged on Curseforge, cause it tells me it supports all these versions including 1.20.6
![Screenshot 2024-05-04 175936](https://github.com/pop4959/Chunky/assets/75923060/1c272c81-f4bd-4950-87c2-7b0b5a1d7756)

I can try your version on Github, but if its not on Curseforge. Modpacks will get deny

**Comment by pop4959** [comment]
Yeah it looks like it's bugged right now, for me it clearly shows 1.20.2 - 1.20.4.

I plan on making another release of chunky soon, but it is not ready yet. Until then, please use the dev builds.

**Comment by pop4959** [comment]
I've published the new versions on CurseForge and Modrinth. Hopefully what seems to be a caching issue is also resolved by now.
