### ISSUE TITLE
suggestion: for modpack devs it would be nice if you can have a config to start a task 

### ISSUE THREAD

**Issue by Thunderrock424242** [pop4959/Chunky#339]
this would be used if a modpack dev needs to pregen a world so server owners don't have to 

it could be like a true or false so people have a option against it. and you can do it just like the command but in the config choose where the player spawns in or world spawn then chose a shape distance and whatever else is needed for the task to begin

**Comment by pop4959** [comment]
This is already possible, you can create the [task file](https://github.com/pop4959/Chunky/wiki/Tasks) ahead of time and set the [continue-on-restart](https://github.com/pop4959/Chunky/wiki/Configuration) option to true which will immediately start generating on startup.

Spawning a player in a specific location is something that is outside of scope for chunky to be handling.

**Comment by Thunderrock424242** [comment]
> This is already possible, you can create the [task file](https://github.com/pop4959/Chunky/wiki/Tasks) ahead of time and set the [continue-on-restart](https://github.com/pop4959/Chunky/wiki/Configuration) option to true which will immediately start generating on startup.
> 
> 
> 
> Spawning a player in a specific location is something that is outside of scope for chunky to be handling.

Not spawning but like pregen of world spawn or where the player is

**Comment by pop4959** [comment]
The center can also be entered in the task. The player usually enters in around the world spawn location.
