### ISSUE TITLE
Config suggestion

### ISSUE THREAD

**Issue by Thunderrock424242** [pop4959/Chunky#340]
So I run out of ram sometimes it would be nice to have a option in the config that if your about to run out of ram it shuts down the task and in the log aka the latests log or in chat it says task canceled out of memory. 

Also another suggestion. Maybe like a time to start like 100 ticks after server starts or 1000 because sometimes the most ram and cpu is used during the first couple of seconds of joining the game.

**Comment by pop4959** [comment]
You can set the amount of memory used by the server or your client. This is the maximum amount of memory chunky will use as well.

For custom task configuration, I recommend looking at the chunky API as you can do both of those things if you would like to, but I have no plans at the moment to build it in as a default option.
