### ISSUE TITLE
Chunky throttles itself when fps is low.

### ISSUE THREAD

**Issue by BurgerBob886** [pop4959/Chunky#341]
I have a mod that lowers my fps down to 2 when I am afk. This is great for afk-ing and when generating or rendering extremely large worlds, as I can make sure resources are not wasted on unnecessarily rendering frames. The problem is that chunky seems to have a feature where it throttles itself to boost fps, which means it's constantly throttling when I am afk. 

What I am asking for is a config option allowing us to disable this feature and run chunky at its max speed all the time.

**Comment by pop4959** [comment]
Chunky does no such thing, it sounds like you have other mods which may be causing issues. If you are still having problems identifying what the issue is, please join our [Discord server](https://discord.gg/ZwVJukcNQG) for help troubleshooting.
