### ISSUE TITLE
Chunky task file type ?

### ISSUE THREAD

**Issue by D7x7z49** [pop4959/Chunky#344]
Could we kindly request to add the file type of **tasks** to the wiki?

I'm terribly sorry, but I'm not sure **how to add files with that type of extension** in config/chunky/tasks. I'm using **Forge**.

**Comment by pop4959** [comment]
They are typically not manually created, but they can be. Start and pause a task to see an example task file generated.

If you have any other questions please join our [Discord server](https://discord.gg/ZwVJukcNQG).
