### ISSUE TITLE
Comes Alive Reborn Incompatibility? 

### ISSUE THREAD

**Issue by sashistillfrvr** [pop4959/Chunky#345]
this plugin is great!, 10/10.

but I got a Watchdog problem while generating chunks on my server cause of Comes Alive Reborn mod. is there incompatibility with chunky and Comes alive mod?
the error is here:
[crash-2024-06-03_03.45.37-server.txt](https://github.com/user-attachments/files/15530914/crash-2024-06-03_03.45.37-server.txt)

and where I think the problem is:
at fabric.net.mca.util.WorldUtils.spawnEntity(WorldUtils.java:51)
at fabric.net.mca.entity.VillagerFactory.spawn(VillagerFactory.java:104)
at fabric.net.mca.server.SpawnQueue.tick(SpawnQueue.java:51)

**Comment by sashistillfrvr** [comment]
I was generating chunks in the overworld and when is on 2.74% the server crashes.

**Comment by pop4959** [comment]
There is not an incompatibility, but there are reported issues with generation using that mod. This is already on their Github issue tracker if you want to follow progress or updates on a fix. Nothing on chunky's end to fix.

If you need help troubleshooting, you may also join the [Discord](https://discord.gg/ZwVJukcNQG) support channel.
