### ISSUE TITLE
[Feature Request] Auto-pause generation when players are online

### ISSUE THREAD

**Issue by a1icja** [pop4959/Chunky#346]
Title. Our server has a lot of unpredictable periods where nobody is online. Ideally, we'd like to generate chunks during these periods and pause while people are online to provide the best experience. Could be a config option, but I don't know how complex it would be to implement. Thank you!

**Comment by pop4959** [comment]
Closing this as a duplicate.

To keep things short and avoid re-explaining everything from prior issues, this basically has no real noticeable impact in performance. Ideally pre-generate before you open up your world to players, but if you are not going to, it doesn't really do much to hurt performance at all considering this is all not run on the main thread and the chunk loading is going to be shared with players (chunky does not prioritize itself over player chunk loading).

If you do believe you are experiencing performance issues while pre-generating with players online, please join the Discord server for support and we can troubleshoot there.
