### ISSUE TITLE
It gives an error when uploading chunks

### ISSUE THREAD

**Issue by singer29** [pop4959/Chunky#348]
Has anyone encountered such a problem that when loading chunks on version 1.21, a crash occurs and the download stops? I use the **Fabric** core, currently only **Chunky** 1.4.16 and **Fabric API** mods. Initially, I thought that the problem was in the server's RAM, instead of **2G** in the start.bat file I put **8G**, the problem has not changed in any way. What could be the reason for this?

[Error.txt](https://github.com/user-attachments/files/15923409/Error.txt)

**Comment by pop4959** [comment]
This doesn't seem to be directly related to chunky. That said, please join the [Discord server](https://discord.gg/ZwVJukcNQG) if you need help troubleshooting this issue, as we may still be able to figure out what is causing it.
