### ISSUE TITLE
Bossbar progress

### ISSUE THREAD

**Issue by Darukshock** [pop4959/Chunky#350]
Hi, I've used this mod a lot and it would be really useful to be able to toggle a bossbar displaying the current progress to OPs.
_Usage_ : enter `/chunky progress bar`
_Chat message_ : `Toggled the progress bossbar on/off` 
_Bossbar_ : Displays numeric infos from the /chunky progress command
Intended for forge

**Comment by pop4959** [comment]
The `chunky silent` command already does this, so just use that if you do not want to see the progress bar or messages.
