### ISSUE TITLE
Chunky not utilizing CPU to full extent

### ISSUE THREAD

**Issue by Barerock** [pop4959/Chunky#354]
Having pregenned before, I noticed that chunky will use 100% of the CPU if given leave to. This time it's hardly working, and usually sitting around 30% with jumps to 50% and 80%, but nothing in the 90s or up. This is causing generation time for smallish radius to be exceedingly long. 5000 is at 4% after 30 minutes, and says it will take between 6 and 15 hours. Before, 5000 could generate 25% in less than an hour at full speed.

I haven't changed any chunk related settings or anything, it's just slow. This seems increasingly like a compatibility error, but I have no idea what could possibly change such a thing like CPU usage.

**Comment by pop4959** [comment]
This is not a bug, please use the [Discord server](https://discord.gg/ZwVJukcNQG) for support and read the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) for performance tips.

**Comment by Barerock** [comment]
> This is not a bug, please use the [Discord server](https://discord.gg/ZwVJukcNQG) for support and read the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) for performance tips.

I read the faq and found nada. Something working and then not working seems like the textbook definition of a bug. The faq also does not include really any info about CPU usage, only RAM, and basic things along the lines of "don't run this on a toaster."

**Comment by pop4959** [comment]
Non-full utilization is normal. This is not considered a bug. Chunky does not decide how much CPU gets used, this is a software and hardware constraint of the chunky system in Minecraft.

If you were seeing CPU usage that was different before, you were running with a different software or hardware configuration with chunky. Please feel free to join the Discord server for more help troubleshooting, as we're willing to help there.
