### ISSUE TITLE
mandatory field in neoforge.mods.toml is deprecated 

### ISSUE THREAD

**Issue by BarionLP** [pop4959/Chunky#355]
Just went through my logs looking for something and found this:

Mod 'chunky' uses deprecated 'mandatory' field in the dependency declaration for 'neoforge'. Use the 'type' field and 'required'/'optional' instead

to fix this change `mandatory=true` to `type="required"` for all dependencies listed in [neoforge.mods.toml](https://github.com/pop4959/Chunky/blob/master/neoforge/src/main/resources/META-INF/neoforge.mods.toml)

**Comment by pop4959** [comment]
Thanks again for the heads-up, updated in 7ba4466fd82c1b78110e5fd11d82127bd2871c51.
