### ISSUE TITLE
[1.21] Fabric server crashing during pregen task

### ISSUE THREAD

**Issue by AndrewGraber** [pop4959/Chunky#358]
Hello! First, just want to say I love the mod and I've been using it across various servers for years. I've been having a problem on my most recent server, where the server is silently crashing while running chunk generation tasks, and not leaving any crash reports.

I am running a modpack on 1.21 with Fabric API 0.100.7, Chunky version 1.4.16. I have noticed that the server's memory usage rises steadily while generating chunks, and wonder if it's a memory problem. It's difficult to tell if this is an issue with Chunky or something else because I have a lot of worldgen mods, and I'm running the server through Pterodactyl panel, which uses Docker instances.

I figured maybe other people also have this issue

**Comment by pop4959** [comment]
Hi, please read the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) for common issues, and join the [Discord support server](https://discord.gg/ZwVJukcNQG) if you need further help troubleshooting crash issues.

My guess is you probably have bad memory allocation under Pterodactyl (over-allocation) and the process is terminated by the operating system.

**Comment by AndrewGraber** [comment]
Yep, it was overallocation. Pterodactyl really shouldn't use the entire container's max ram as the default server Xmx lol

**Comment by pop4959** [comment]
You're telling me, this gets at least a dozen people a week! 😆 

Glad to hear you figured it out.
