### ISSUE TITLE
Possible incompatibility with Moonrise.

### ISSUE THREAD

**Issue by EterNityCH** [pop4959/Chunky#360]
**Server version:** neoforge-21.1.23

**Mod installed:** Chunky-1.4.16, Moonrise-NeoForge-0.1.0-SNAPSHOT+522e1bc

**Server logs**: [https://mclo.gs/TLBYZpN](https://mclo.gs/TLBYZpN)

[Chunky] Task started in minecraft:overworld for the square region centered at 0, 0 with radius 10000.
[Chunky] Task running for minecraft:overworld. Processed: 3745 chunks (0.24%), ETA: 0:00:41, Rate: 37450.0 cps, Current: 28, -4
[Chunky] Task running for minecraft:overworld. Processed: 280041 chunks (17.89%), ETA: 0:00:05, Rate: 254351.5 cps, Current: -215, 273
[Chunky] Task running for minecraft:overworld. Processed: 575953 chunks (36.80%), ETA: 0:00:03, Rate: 274002.4 cps, Current: 75, -361
[Chunky] Task running for minecraft:overworld. Processed: 885079 chunks (56.55%), ETA: 0:00:02, Rate: 285233.3 cps, Current: 481, -257
[Chunky] Task running for minecraft:overworld. Processed: 1193374 chunks (76.25%), ETA: 0:00:01, Rate: 290783.1 cps, Current: -534, -227
[Chunky] Task running for minecraft:overworld. Processed: 1502546 chunks (96.01%), ETA: 0:00:00, Rate: 294328.3 cps, Current: -497, 611
[Chunky] Task finished for minecraft:overworld. Processed: 1565001 chunks (100.00%), Total time: 0:00:05

**Actions to reproduce:**

Start server, type in **/chunky radius 10,000** then **/chunky start**

### Sit and watch it go brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

I dont think any chunk is actually generated.

😕 *confused noise*

**Comment by pop4959** [comment]
Fixed, thanks @DrexHD :)

**Comment by streifen-dev** [comment]
Would it be possible to backport this to a NeoForge 1.21.1 release? Currently a lot of modpacks are still stuck at that version

**Comment by pop4959** [comment]
> Would it be possible to backport this to a NeoForge 1.21.1 release? Currently a lot of mods modpacks are still stuck at that version

Does the current version not already work on 1.21.1? Keep in mind this is not the latest release but the latest compatible dev build for 1.21.1. See #379.

**Comment by streifen-dev** [comment]
I somehow completely missed that thread, sorry about that!

I grabbed the version off your codemc and it works. Thanks!
