### ISSUE TITLE
Chunky CPS Problem

### ISSUE THREAD

**Issue by TexiderWare** [pop4959/Chunky#363]
I'm loading a -36864 -18432 36863 18431 area with Chunky on my dedicated server, but I'm only getting around 30 CPS. How can I increase this value to 200 - 400 CPS? My CPU is a Ryzen 9 5950X 16-Core, and I have 256GB of RAM.

Start.bat
set fileName="Spigot.jar"
set /A memory=200

"C:\Program Files\Zulu\zulu-21\bin\java.exe" -Xms%memory%G -Xmx%memory%G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -DPaper.IgnoreJavaVersion=true -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -jar Spigot.jar --nogui

**Comment by pop4959** [comment]
Yes please read the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) and join our Discord if you need more help.
