### ISSUE TITLE
1.20.x Update

### ISSUE THREAD

**Issue by DaDisciple** [pop4959/Chunky#371]
Hello there, I would like to have a updated version of this mod for 1.20.1. Also would love to know if there were major changes in the newer versions of the mod, in the sense I'd like to know if i'm missing something by using a unupdated version of it before even receiving any update.
(Changelogs don't really mention anything at all in every update... so...)

**Comment by pop4959** [comment]
There are not really many changes in the latest version for 1.20.1. The only change is Moonrise support, but there will be one last final release for 1.20.1 before moving on to 1.20.2/1.20.3. Don't worry!

If you have any specific questions or would like to discuss further, please join our Discord server.

**Comment by DaDisciple** [comment]
> There are not really many changes in the latest version for 1.20.1. The only big change is Moonrise support, but there will be one last final release for 1.20.1 before moving on to 1.20.2/1.20.3. Don't worry!
> 
> If you have any specific questions or would like to discuss further, please join our Discord server.

Thank you very much for the response. Appreciate it!
