### ISSUE TITLE
Stuck mid chunk generation and can't recover

### ISSUE THREAD

**Issue by MateusRoscoe** [pop4959/Chunky#372]
When I try to generate a bigger radius (500 to 1000+) around spawn I always get stuck mid progress with CPS dropping from 30\~40 to under 2 and then it completely freezes, if I cancel the chunk generation the memory usage does not lower and if I try to stop my server it will be infinitely trying to save the world until I force close it. It usually dies around 3\~4GB of RAM usage but this is my user_jvm_args `-Xmx16G -Xms2G`.

![image](https://github.com/user-attachments/assets/29241880-9592-44b4-8122-cad2bcba72dc)

I'm utilizing NeoForge version 21.1.73 in minecraft 1.21.1 with Java 21 and chunky 1.4.16 for NeoForge. My setup is 32GB of DDR4 and a Ryzen 5 5600X

This is my modlist 
`
 Mod List:
                Name Version (Mod Id)

                Additional Lights 2.1.9 (additional_lights)
                Almanac 1.0.2 (almanac)
                Amendments 1.21-1.2.18 (amendments)
                Apothic Attributes 2.4.0 (apothic_attributes)
                Apothic Enchanting 1.2.3 (apothic_enchanting)
                Apothic Spawners 1.1.1 (apothic_spawners)
                AppleSkin 3.0.5+mc1.21 (appleskin)
                Aquaculture 2 2.7.10 (aquaculture)
                Architectury 13.0.8 (architectury)
                Artifacts 12.0.5 (artifacts)
                Artifacts Delight 1.0.0-1.21.x (artifactsdelight)
                Athena 4.0.1 (athena)
                AttributeFix 21.1.2 (attributefix)
                Balm 21.0.20 (balm)
                Bartering Station 21.1.0 (barteringstation)
                Better Advancements 0.4.3.21 (betteradvancements)
                Better Beds 1.4.0 (betterbeds)
                Better Combat 2.0.3+1.21.1 (bettercombat)
                Better Tridents 21.1.0 (bettertridents)
                Biomes O' Plenty 21.1.0.7 (biomesoplenty)
                Biomes O'Plenty Delight 1.0.1.4-1.21.x (biomesoplentydelight)
                Bookshelf 21.1.13 (bookshelf)
                Chisel Reborn 1.8.2 (chisel)
                ChoiceTheorem's Overhauled Village 3.5.3a (ctov)
                Chunk Loaders 1.2.8 (chunkloaders)
                Chunky 1.4.16 (chunky)
                Cloth Config v15 API 15.0.140 (cloth_config)
                Clumps 19.0.0.1 (clumps)
                Combat Roll 2.0.1+1.21.1 (combat_roll)
                Comforts 9.0.3+1.21.1 (comforts)
                Common Networking 1.0.16-1.21.1 (commonnetworking)
                CommonGroovyLibrary 0.5.1 (commongroovylibrary)
                Connected Glass 1.1.12 (connectedglass)
                ConnectedTexturesMod 1.21-1.2.1+3 (ctm)
                Connector Extras 1.12.1+1.21.1 (connectorextras)
                Connector Extras EMI Bridge 1.12.1+1.21.1 (connectorextras_emi_bridge)
                Connector Extras Energy Bridge 1.12.1+1.21.1 (connectorextras_energy_bridge)
                Connector Extras JEI Bridge 1.12.1+1.21.1 (connectorextras_jei_bridge)
                Connector Extras KubeJS Bridge 1.12.1+1.21.1 (connectorextras_kubejs_bridge)
                Connector Extras ModMenu Bridge 1.12.1+1.21.1 (connectorextras_modmenu_bridge)
                Connector Extras Pehkui Bridge 1.12.1+1.21.1 (connectorextras_pehkui_bridge)
                Connector Extras REI Bridge 1.12.1+1.21.1 (connectorextras_rei_bridge)
                Connector Extras Terrablender Bridge 1.12.1+1.21.1 (connectorextras_terrablender_bridge)
                Controlling 19.0.3 (controlling)
                Crafting On A Stick 1.21.0.1 (crafting_on_a_stick)
                Crafting Tweaks 21.1.3 (craftingtweaks)
                CreativeCore 2.12.21 (creativecore)
                Creeper Overhaul 4.0.5 (creeperoverhaul)
                Cristel Lib 1.2.8 (cristellib)
                Cupboard mod 2.8 (cupboard)
                Curios API 9.0.14+1.21.1 (curios)
                Diagonal Blocks 21.1.0 (diagonalblocks)
                Diagonal Fences 21.1.0 (diagonalfences)
                Diagonal Walls 21.1.0 (diagonalwalls)
                Diagonal Windows 21.1.0 (diagonalwindows)
                Dis-Enchanting Table 3.1.0 (disenchanting_table)
                Distinguished Potions 21.1.0 (distinguishedpotions)
                Durability Tooltip 1.1.5 (durabilitytooltip)
                Easy Anvils 21.1.0 (easyanvils)
                Easy Magic 21.1.0 (easymagic)
                Easy Shulker Boxes 21.1.0 (easyshulkerboxes)
                Effect Descriptions 21.1.0 (effectdescriptions)
                ElevatorMod 1.21.1-1.11.3 (elevatorid)
                EntityCulling 1.7.1 (entityculling)
                ExpandAbility 12.0.0 (expandability)
                Explorer's Compass 1.21.1-3.0.3-neoforge (explorerscompass)
                Extended Industrialization 1.9.4-beta-1.21.1 (extended_industrialization)
                Farmer's Delight 1.2.4a (farmersdelight)
                Fast Workbench 9.1.2 (fastbench)
                fastasyncworldsave mod 2.0 (fastasyncworldsave)
                FastFurnace 9.0.0 (fastfurnace)
                Ferrite Core 7.0.2 (ferritecore)
                Forgified Fabric API 0.104.0+2.0.16+1.21.1 (fabric_api)
                Forgified Fabric API Base 0.4.42+d1308ded19 (fabric_api_base)
                Forgified Fabric API Lookup API (v1) 1.6.68+c21168c319 (fabric_api_lookup_api_v1)
                Forgified Fabric Biome API (v1) 13.0.29+1e62d33c19 (fabric_biome_api_v1)
                Forgified Fabric Block API (v1) 1.0.22+a6e994cd19 (fabric_block_api_v1)
                Forgified Fabric BlockRenderLayer Registration (v1) 1.1.52+b089b4bd19 (fabric_blockrenderlayer_v1)
                Forgified Fabric BlockView API (v2) 1.0.10+9afaaf8c19 (fabric_block_view_api_v2)
                Forgified Fabric Client Tags 1.1.15+e053909619 (fabric_client_tags_api_v1)
                Forgified Fabric Command API (v2) 2.2.28+36d727be19 (fabric_command_api_v2)
                Forgified Fabric Content Registries (v0) 8.0.16+0a0c14ff19 (fabric_content_registries_v0)
                Forgified Fabric Convention Tags 2.0.22+7f945d5b19 (fabric_convention_tags_v1)
                Forgified Fabric Convention Tags (v2) 2.7.0+d13df91319 (fabric_convention_tags_v2)
                Forgified Fabric Data Attachment API (v1) 1.1.28+d82d50ba19 (fabric_data_attachment_api_v1)
                Forgified Fabric Data Generation API (v1) 20.2.19+ed29d49b19 (fabric_data_generation_api_v1)
                Forgified Fabric Entity Events (v1) 1.7.0+34c3dc2d19 (fabric_entity_events_v1)
                Forgified Fabric Events Interaction (v0) 0.7.12+7b71cc1619 (fabric_events_interaction_v0)
                Forgified Fabric Game Rule API (v1) 1.0.53+36d727be19 (fabric_game_rule_api_v1)
                Forgified Fabric Game Test API (v1) 2.0.4+29f188ce19 (fabric_gametest_api_v1)
                Forgified Fabric Item API (v1) 11.0.0+f56196c219 (fabric_item_api_v1)
                Forgified Fabric Item Group API (v1) 4.1.5+e324903319 (fabric_item_group_api_v1)
                Forgified Fabric Key Binding API (v1) 1.0.47+62cc7ce119 (fabric_key_binding_api_v1)
                Forgified Fabric Lifecycle Events (v1) 2.3.12+88bf4f7f19 (fabric_lifecycle_events_v1)
                Forgified Fabric Loot API (v2) 3.0.14+a3ee712d19 (fabric_loot_api_v2)
                Forgified Fabric Loot API (v3) 1.0.2+333dfad919 (fabric_loot_api_v3)
                Forgified Fabric Message API (v1) 6.0.13+e053909619 (fabric_message_api_v1)
                Forgified Fabric Model Loading API (v1) 2.0.0+a6e994cd19 (fabric_model_loading_api_v1)
                Forgified Fabric Networking API (v1) 4.2.2+a6c6b14f19 (fabric_networking_api_v1)
                Forgified Fabric Object Builder API (v1) 15.2.0+ba60825e19 (fabric_object_builder_api_v1)
                Forgified Fabric Particles (v1) 4.0.2+824f924c19 (fabric_particles_v1)
                Forgified Fabric Recipe API (v1) 5.0.12+59440bcc19 (fabric_recipe_api_v1)
                Forgified Fabric Registry Sync (v0) 5.1.2+0c9b5b5419 (fabric_registry_sync_v0)
                Forgified Fabric Renderer - Indigo 1.7.0+acb05a3919 (fabric_renderer_indigo)
                Forgified Fabric Renderer API (v1) 3.4.0+acb05a3919 (fabric_renderer_api_v1)
                Forgified Fabric Rendering (v1) 5.0.5+077ba95f19 (fabric_rendering_v1)
                Forgified Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19 (fabric_rendering_data_attachment_v1)
                Forgified Fabric Rendering Fluids (v1) 3.1.6+857185bc19 (fabric_rendering_fluids_v1)
                Forgified Fabric Resource Conditions API (v1) 4.3.0+edeecbd819 (fabric_resource_conditions_api_v1)
                Forgified Fabric Resource Loader (v0) 1.3.0+bcae32ce19 (fabric_resource_loader_v0)
                Forgified Fabric Screen API (v1) 2.0.25+b282c4bb19 (fabric_screen_api_v1)
                Forgified Fabric Screen Handler API (v1) 1.3.86+8dbc56dd19 (fabric_screen_handler_api_v1)
                Forgified Fabric Sound API (v1) 1.0.23+10b84f8419 (fabric_sound_api_v1)
                Forgified Fabric Transfer API (v1) 5.2.0+aab4c96e19 (fabric_transfer_api_v1)
                Forgified Fabric Transitive Access Wideners (v1) 6.1.0+0df3143b19 (fabric_transitive_access_wideners_v1)
                Functional Storage 1.21.1-1.3.5 (functionalstorage)
                Fusion 1.1.1+a (fusion)
                GeckoLib 4 4.6.6 (geckolib)
                GlitchCore 2.1.0.0 (glitchcore)
                Grand Power 3.0.0 (grandpower)
                GroovyModLoader 6.0.1 (gml)
                Horse Expert 21.1.0 (horseexpert)
                HorseBuff 2.1.8 (horsebuff)
                Industrial Foregoing 1.21-3.6.15 (industrialforegoing)
                Inventory Tweaks Refoxed 1.21.0-1.1.4 (invtweaks)
                Iron Furnaces 4.2.6 (ironfurnaces)
                Item Collectors 1.1.10 (itemcollectors)
                Item Interactions 21.1.0 (iteminteractions)
                Jade 15.8.2+neoforge (jade)
                Journeymap 1.21.1-6.0.0-beta.29 (journeymap)
                JourneyMap API 2.0.0 (journeymap_api)
                Just Enough Breeding 1.4.0 (justenoughbreeding)
                Just Enough Effects Descriptions 1.21-2.2.8 (jeed)
                KumaAPI 21.0.5-SNAPSHOT (kuma_api)
                Leaves Be Gone 21.1.0 (leavesbegone)
                Let Me Despawn 1.4.4 (letmedespawn)
                Lithium 0.14.0-snapshot+mc1.21.1-build.88 (lithium)
                Lithostitched 1.3.4 (lithostitched)
                Living Things 1.21.1-2.1.3 (livingthings)
                Macaw's Bridges 3.0.0 (mcwbridges)
                Macaw's Bridges - BOP 1.21-1.0 (macawsbridgesbop)
                Macaw's Doors 1.1.1 (mcwdoors)
                Macaw's Fences - BOP 1.21-1.1 (mcwfencesbop)
                Macaw's Fences and Walls 1.1.2 (mcwfences)
                Macaw's Furniture 3.3.0 (mcwfurnitures)
                Macaw's Furnitures - BOP 1.21.1-1.0 (mcwfurnituresbop)
                Macaw's Lights and Lamps 1.1.1 (mcwlights)
                Macaw's Paintings 1.0.5 (mcwpaintings)
                Macaw's Roofs 2.3.1 (mcwroofs)
                Macaw's Roofs - BOP 1.21-1.0 (macawsroofsbop)
                Macaw's Trapdoors 1.1.3 (mcwtrpdoors)
                Macaw's Windows 2.3.2 (mcwwindows)
                Magnum Torch 21.1.0 (magnumtorch)
                Measurements 3.0.0 (measurements)
                Mineblock's Repeated Utilities 1.0.4+1.21+neoforge (mru)
                Minecraft 1.21.1 (minecraft)
                MmmMmmMmmMmm 1.21-2.0.6 (dummmmmmy)
                Mob Lassos 21.1.0 (moblassos)
                Modern Dynamics 0.9.2 (moderndynamics)
                Modern Industrialization 2.2.25 (modern_industrialization)
                ModernFix 5.19.3+mc1.21.1 (modernfix)
                MonoLib 1.4.1 (monolib)
                Moonlight Lib 1.21-2.15.8 (moonlight)
                Nature's Compass 1.21.1-3.0.2-neoforge (naturescompass)
                NeoForge 21.1.73 (neoforge)
                Noisium 2.3.0+mc1.21-1.21.1 (noisium)
                Nullscape 1.2.9 (nullscape)
                Overflowing Bars 21.1.1 (overflowingbars)
                Patchouli 1.21-87-NEOFORGE-SNAPSHOT (patchouli)
                Pick Up Notifier 21.1.0 (pickupnotifier)
                Placebo 9.5.4 (placebo)
                Player Animator 2.0.0-alpha1+1.21 (playeranimator)
                Plenty Plates 21.1.0 (plentyplates)
                Polymorph 1.0.6+1.21.1 (polymorph)
                PrickleMC 21.1.6 (prickle)
                Puzzles Lib 21.1.22 (puzzleslib)
                Railcraft Reborn 1.2.2 (railcraft)
                Reap Mod 1.21.1-1.1.2 (reap)
                Resourceful Lib 3.0.11 (resourcefullib)
                Resourcefulconfig 3.0.4 (resourcefulconfig)
                Respawning Animals 21.1.0 (respawninganimals)
                Roughly Enough Items (REI) 16.0.788 (roughlyenoughitems)
                Searchables 1.0.2 (searchables)
                Silent Gear 4.0.8 (silentgear)
                Silent Lib 10.3.0 (silentlib)
                Simple Backups 1.21-4.0.7 (simplebackups)
                Simple Magnets 1.1.12 (simplemagnets)
                Sinytra Connector 2.0.0-beta.3+1.21.1 (connector)
                Smarter Farmers 1.21-2.1.5 (smarterfarmers)
                Sophisticated Backpacks 3.20.18 (sophisticatedbackpacks)
                Sophisticated Core 0.6.47 (sophisticatedcore)
                SpectreLib 0.17.2+1.21 (spectrelib)
                Spiky Spikes 21.1.0 (spikyspikes)
                Storage Delight 24.09.11-1.21-neoforge (storagedelight)
                Stylish Effects 21.1.0 (stylisheffects)
                SuperMartijn642's Config Library 1.1.8 (supermartijn642configlib)
                SuperMartijn642's Core Lib 1.1.17+i (supermartijn642corelib)
                TerraBlender 4.1.0.5 (terrablender)
                Terralith 2.5.6 (terralith)
                Tesseract API 1.5.4-beta-1.21.1 (tesseract_api)
                Titanium 4.0.24 (titanium)
                Tom's Simple Storage Mod 2.0.10 (toms_storage)
                Towns and Towers 1.13.2 (t_and_t)
                Trading Post 21.1.0 (tradingpost)
                Universal Bone Meal 21.1.0 (universalbonemeal)
                Utilitarian 1.21.1-0.13.4 (utilitarian)
                Visual Workbench 21.1.0 (visualworkbench)
                Waystones 21.1.5 (waystones)
                YUNG's API 1.21.1-NeoForge-5.1.2 (yungsapi)
                YUNG's Better Desert Temples 1.21.1-NeoForge-4.1.2 (betterdeserttemples)
                YUNG's Better Dungeons 1.21.1-NeoForge-5.1.2 (betterdungeons)
                YUNG's Better End Island 1.21.1-NeoForge-3.1.1 (betterendisland)
                YUNG's Better Jungle Temples 1.21.1-NeoForge-3.1.1 (betterjungletemples)
                YUNG's Better Mineshafts 1.21.1-NeoForge-5.1.1 (bettermineshafts)
                YUNG's Better Nether Fortresses 1.21.1-NeoForge-3.1.2 (betterfortresses)
                YUNG's Better Ocean Monuments 1.21.1-NeoForge-4.1.1 (betteroceanmonuments)
                YUNG's Better Strongholds 1.21.1-NeoForge-5.1.2 (betterstrongholds)
                YUNG's Better Witch Huts 1.21.1-NeoForge-4.1.1 (betterwitchhuts)
                YUNG's Bridges 1.21.1-NeoForge-5.1.1 (yungsbridges)
                YUNG's Extras 1.21.1-NeoForge-5.1.1 (yungsextras)
`

**Comment by pop4959** [comment]
Hi, this usually isn't a bug, but rather an issue with either server memory allocation or mods in your mod pack. Github is not really the place for this; I recommend checking out our [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) first, and joining the [Discord server](https://discord.gg/ZwVJukcNQG) if you still need help troubleshooting.

**Comment by HAQ20** [comment]
I have the exact same problem did you find out what was wrong?

**Comment by pop4959** [comment]
> I have the exact same problem did you find out what was wrong?

Hey! Instead of necroing old issues, please join the Discord server for troubleshooting and support, as mentioned above. Many freeze issues can look similar but can be caused by different mods. Often this requires thorough testing.
