### ISSUE TITLE
Chunky is not starting to generate chunks

### ISSUE THREAD

**Issue by JustHmm** [pop4959/Chunky#376]
![image](https://github.com/user-attachments/assets/bbce9f6e-e06b-4bd4-a97d-2f789d83cef4)
MC 1.20.1, Fabric 0.16.9, Chunky 1.3.146 (and some other mods)
There is no crash, it just not starting.
config/chunky/tasks/minecraft/overworld.properties  
```
world=minecraft:overworld
cancelled=true
center-x=-34.5
center-z=-422.5
radius=100.0
shape=square
pattern=region
chunks=225
time=1
```
config
```
  "version": 2,
  "language": "en",
  "continueOnRestart": false,
  "forceLoadExistingChunks": false,
  "silent": false,
  "updateInterval": 1
```
edit: After joining to singleplayer world, it worked like 10 seconds than stopped again and never worked.  I did restart minecraft again to confirm that "it works like first 10 seconds" but it didn't worked again.

**Comment by pop4959** [comment]
Hi, this is not a bug. It looks like chunky completed the 100 block radius in 1ms which is quite expected especially if the region is already generated. Chunks only generates once, so re-running the commands several times will not have much of an effect. If you want to generate more chunks, increase the radius.

Please join the Discord server for support if you are still having difficulties. Thanks!
