### ISSUE TITLE
need limit cps

### ISSUE THREAD

**Issue by makegodhere** [pop4959/Chunky#377]
Need to limit resources util for background task.
For example limit cps in config.

**Comment by pop4959** [comment]
Chunky does not have a way to limit cps built-in. This is dependent on your server. Please read the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) and apply suggestions for speeding up in reverse if you want to slow it down (e.g. reduce the number of threads the server is using for generation). If you have any other questions, please join the [Discord server](https://discord.gg/ZwVJukcNQG).
