### ISSUE TITLE
Feature: Set core usage

### ISSUE THREAD

**Issue by artman41** [pop4959/Chunky#380]
It'd be nice if Chunky was able to be given a target amount of cores to use;

I am trying to generate a 10kx10k Chunk radius using the Square shape on a Ryzen 9 7950X3D on WIndows 11

Looking in task manager, I'm only seeing 16 of the 32 available logical processors being used.

![image](https://github.com/user-attachments/assets/0f51cbcb-cc66-4a64-aec8-ef72dc7b60fe)

Chunky will often start at ~30cps but will quickly drop to ~15cps and lower, usually running at between 4cps - 10cps where it'll often sit at either ~4cps or ~9cps.

There are spikes to 20cps+ but they are infrequent.

[chunk_cps.txt](https://github.com/user-attachments/files/17911410/chunk_cps.txt)

According to Process Hacker, CPU usage peaks at 15%

![image](https://github.com/user-attachments/assets/336fb90e-9dc5-4a9d-8851-dedfeedd1494)

Ideally I'd like to see a prompt available within Chunky (whether as part of a command or a config file) that will force it to attempt to use all of the CPU available

**Comment by pop4959** [comment]
Chunky is not responsible for managing how much CPU is used. Please see previous issues asking about this and read the FAQ for more information. If you have any other questions join the chunky Discord server.

**Comment by kue7heh** [comment]
Use c2me
