### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by mxtilx** [pop4959/Chunky#384]
了解到chunky trim world square 0 0 0 0 outside 0 可以删除玩家未加载过的区块，能否升级为玩家从未修改过的区块类似于”No Unused Chunks”，但我从未找到一个有类似功能的plugin

**Comment by pop4959** [comment]
It already does this. Please see the [wiki](https://github.com/pop4959/Chunky/wiki/Commands#trim) for more information.

This uses the "InhabitedTime" value of the chunks which you can read about [here](https://minecraft.wiki/w/Chunk_format). If the value is 0 then a player has never been in that chunk, and it has never been modified by a player.

**Comment by pop4959** [comment]
Yes that is how that works and is intended. There isn't a way to detect if a player has placed a block or not. That is not within scope for Chunky to check. This works as intended.
