### ISSUE TITLE
Display Chunky task progress to player who starts the task

### ISSUE THREAD

**Issue by Noxillio** [pop4959/Chunky#55]
It'd be nice to be able to see it in chat, preferably make it togglable so people who don't like the spam don't have to see it

**Comment by pop4959** [comment]
Yeah, like WorldBorder right? Low priority for now, but I've gotten this suggestion on our Discord server before. I'll consider it.

**Comment by pop4959** [comment]
I've added a `/chunky progress` command to show the same information normally seen from the console in-game. Hopefully this addresses the need for checking in-game without all the spam! 😄
