### ISSUE TITLE
Discord to talk about Crowdin (and maybe other stuff)+Wiki

### ISSUE THREAD

**Issue by toinouH** [pop4959/Chunky#62]
I was contributing on crowdin (French) and I had questions about what you did and what you want.
Crowdin's discution system is not the best so I'm here to request you an invite for a Discord where we could not.

I have though we could translate the wiki too ^^.

Thank you for reading.

**Comment by pop4959** [comment]
Hello! Thank you for your interest in translating. We currently have a #chunky channel on the [MOSS (Minecraft Open Source Software) Discord](https://discord.gg/PHpuzZS) where we usually discuss the plugin. Feel free to join us there.

Keep in mind that the Crowdin integration is new and I'm not 100% sure that it is working correctly yet. If there are any issues please let me know and I will try to resolve them as soon as possible.

**Comment by pop4959** [comment]
I've merged your translations, they look good to me.
