### ISSUE TITLE
[Feature] Built-In UI Similar to Chunk Pregenerator on Forge

### ISSUE THREAD

**Issue by ZaneDragonBorn** [pop4959/Chunky#64]
I always loved Pregenerating with [Chunk Pregenerator's](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator) Interface. It was a legit Pre-generator. Please make a UI for the Mod that works like that mod did

**Comment by pop4959** [comment]
Latest development build adds a progress bar feature, so now you can watch the progress visually from in-game just like on Forge.
