### ISSUE TITLE
[noob] do I have to give the bot op or anything?

### ISSUE THREAD

**Issue by AimPizza** [pop4959/Chunky#66]
The only command I see ingame is the /chunkinfo but in a Tutorial he has all the commands

**Comment by Yey007** [comment]
The commands require op to use by default. You can change this with a permissions plugin, but otherwise you will need op.

**Comment by AimPizza** [comment]
How do I give op to the bot tough?

**Comment by Yey007** [comment]
The bot? There is no bot. I'm not quite sure what you mean.

**Comment by pop4959** [comment]
Sorry if I don't fully understand your question. What platform are you currently running under? Paper, Fabric, etc.

Commands should be available with the permission `chunky.chunky` or with OP. If in single player, please enable cheats on the world.

**Comment by AimPizza** [comment]
I think this is the problem, is there a way to run it with forge?

**Comment by pop4959** [comment]
There isn't any version that runs natively on Forge currently, on 1.12.2 you can use the Sponge version if you have it installed as a mod on your server.

**Comment by AimPizza** [comment]
But there is no way to run it on 1.16.4?

**Comment by Yey007** [comment]
No, because there is no sponge implementation for > 1.16.4

**Comment by AimPizza** [comment]
Okay. I'm sorry for asking such dumb questions tho and thank both of you very much 
have a nice day

**Comment by Yey007** [comment]
@AimPizza I apologize, I should have been more clear. You can run it on 1.16.4 HOWEVER you cannot run it with Forge mods. If you use something like Paper or Fabric, you can run on the latest version.

**Comment by pop4959** [comment]
He's trying to run it on Forge. There isn't a native Forge version yet for 1.16.4, nor is Sponge updated to 1.16.4 yet. It should be possible eventually once Sponge updates.
