### ISSUE TITLE
Requires update for Mod Menu

### ISSUE THREAD

**Issue by FewerFlaws** [pop4959/Chunky#69]
Mod menu changed recently and the icon here is now invalid:
`[21:50:43] [main/WARN]: Warning! Mod chunky-fabric has a broken icon, loading default icon`

**Comment by pop4959** [comment]
How are you accessing this mod menu? I'm familiar with the one on Forge but I have not seen it in Fabric.

**Comment by pop4959** [comment]
I was made aware that this is itself a mod. Added support in d645eeb119f715eeeb0c2b96e0b7c51d3c128fcc, you can download the latest version [here](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/125/).
