### ISSUE TITLE
Chunk deletion

### ISSUE THREAD

**Issue by quick007YT** [pop4959/Chunky#80]
I think a feature that would go really well with chunky would be chunk deletion. On some servers, people use elytras to generate massive amounts of chunks that use storage space, so I think being able to delete chunks that haven't been entered for x days if no modifications were made o the chunk would be a nice feature. Chunky-generated chunks obviously wouldn't be deleted here.

**Comment by pop4959** [comment]
Closing as a duplicate of #20. Trim (which deletes chunks) is already available in the latest release on Spigot.
