### ISSUE TITLE
Automatically pause and continue depending on the amount of players online

### ISSUE THREAD

**Issue by Kore-Development** [pop4959/Chunky#81]
Automatically resume pre-generation while either no players are on or no players without a specific permission like `chunky.ignore` or similar. When a player that doesn't fit that criteria joins then pre-generation would pause. There would be a config option to disable this.

**Comment by pop4959** [comment]
Hey, thanks for the suggestion! This looks pretty similar to #29, have you seen that issue? I'm currently planning on implementing something like that in an upcoming update, so please comment there and leave any feedback on it you might have.

**Comment by pop4959** [comment]
This hasn't been added yet, but I'm going to close this in favor of #29. Please keep an eye on that issue for further updates on this.
