### ISSUE TITLE
'/chunky status' command to check the progress.

### ISSUE THREAD

**Issue by RDKRACZ** [pop4959/Chunky#84]
or '/chunky progress'
Right now it only gets printed in the console.

**Comment by pop4959** [comment]
Thanks, yeah this should be an easy add when I get around to it. I've already got it on my TODO along with a billion other things I still plan on doing with this plugin. 😄

May also come along with #55 if I add that.

**Comment by pop4959** [comment]
In latest dev builds it's possible to use the command `/chunky progress` to view the progress from in-game. It shows the same information as normally seen in the console.

As an added bonus, if you are using Fabric there is also a progress bar now too. 😄
