### ISSUE TITLE
Bug with Worldborder selection

### ISSUE THREAD

**Issue by Spaex** [pop4959/Chunky#94]
I've created a World with Multiverse on Paper-584 for Minecraft 1.16.5 and did set the worldborder using the vanilla command to 10000 Blocks (Meaning 5000 Radius). 
When I use "/chunky worldborder" it takes the right center but it takes 1500 as Radius.
Am I doing something wrong or is that a bug?

**Comment by Spaex** [comment]
My fault forgot to change the world via /chunky world

**Comment by pop4959** [comment]
No problem, glad you figured it out before I had a chance to respond! Hopefully it's not too confusing. I do know people sometimes get this confused (especially when using in-game and expecting it to be their current world, though chunky is mostly intended to be used from the console / offline).
