### ISSUE TITLE
Reporting as running, but not

### ISSUE THREAD

**Issue by rueckl** [pop4959/Chunky#98]
So, I am trying to pregen my world.

I set everything up and use the "/chunky start" command.

It shows me the message that it started, but no update on the progress or any CPU usage. It just gives me the message 
"[12:45:36 INFO]: [Bukkit] [Chunky] Task started for 2 idiotas at 0, 0 with radius 500.".

When I try to stop it, it says that it's running, but it is not.

Am I missing something?
![chunky](https://user-images.githubusercontent.com/9300021/120674586-9d536d80-c46a-11eb-9dfd-819948a3c343.PNG)

**Comment by pop4959** [comment]
Did you run the `chunky silent` command? That will toggle all update messages.

If it's not that, I recommend joining the #chunky channel on the [MOSS Discord](https://discord.gg/PHpuzZS) I can look into this a bit more with you. I haven't seen anyone have an issue like this yet.

**Comment by rueckl** [comment]
It was an issue with one of my codes conflicting with it. Fixed it. Sorry for the incovenience.

**Comment by pop4959** [comment]
Glad to hear that you figured it out. Is it something that you would be able to explain (in case it happens again for someone else)?
